// This file is generated by bsg_multiplier_compressor.py 8 8. Do not modify.
module bsg_multiplier_compressor_8_8
(
  input [1:0][11:0] base_i
  ,input [3:0][10:0] psum_i
  ,input [3:0] sign_modification_i
  ,output [15:0] outA_o
  ,output [15:0] outB_o
);
wire csa_0_0_res_o;
wire csa_0_0_car_o;
wire csa_0_1_res_o;
wire csa_0_1_car_o;
wire csa_0_2_res_o;
wire csa_0_2_car_o;
wire csa_0_3_res_o;
wire csa_0_3_car_o;
wire csa_0_4_res_o;
wire csa_0_4_car_o;
wire csa_0_5_res_o;
wire csa_0_5_car_o;
wire csa_0_6_res_o;
wire csa_0_6_car_o;
wire csa_0_7_res_o;
wire csa_0_7_car_o;
wire csa_0_8_res_o;
wire csa_0_8_car_o;
wire csa_0_9_res_o;
wire csa_0_9_car_o;
wire csa_0_10_res_o;
wire csa_0_10_car_o;
wire csa_0_11_res_o;
wire csa_0_11_car_o;
wire csa_0_12_res_o;
wire csa_0_12_car_o;
wire csa_0_13_res_o;
wire csa_0_13_car_o;
wire csa_0_14_res_o;
wire csa_0_14_car_o;
wire csa_0_15_res_o;
wire csa_0_15_car_o;
wire csa_0_16_res_o;
wire csa_0_16_car_o;
wire csa_0_17_res_o;
wire csa_0_17_car_o;
wire csa_0_18_res_o;
wire csa_0_18_car_o;
wire csa_0_19_res_o;
wire csa_0_19_car_o;
wire csa_0_20_res_o;
wire csa_0_20_car_o;
wire csa_0_21_res_o;
wire csa_0_21_car_o;
wire csa_0_22_res_o;
wire csa_0_22_car_o;
wire csa_1_0_res_o;
wire csa_1_0_car_o;
wire csa_1_1_res_o;
wire csa_1_1_car_o;
wire csa_1_2_res_o;
wire csa_1_2_car_o;
wire csa_1_3_res_o;
wire csa_1_3_car_o;
wire csa_1_4_res_o;
wire csa_1_4_car_o;
wire csa_1_5_res_o;
wire csa_1_5_car_o;
wire csa_1_6_res_o;
wire csa_1_6_car_o;
wire csa_1_7_res_o;
wire csa_1_7_car_o;
wire csa_1_8_res_o;
wire csa_1_8_car_o;
wire csa_1_9_res_o;
wire csa_1_9_car_o;
wire csa_1_10_res_o;
wire csa_1_10_car_o;
wire csa_1_11_res_o;
wire csa_1_11_car_o;
wire csa_1_12_res_o;
wire csa_1_12_car_o;
wire csa_1_13_res_o;
wire csa_1_13_car_o;
wire csa_1_14_res_o;
wire csa_1_14_car_o;
wire csa_2_0_res_o;
wire csa_2_0_car_o;
wire csa_2_1_res_o;
wire csa_2_1_car_o;
wire csa_2_2_res_o;
wire csa_2_2_car_o;
wire csa_2_3_res_o;
wire csa_2_3_car_o;
wire csa_2_4_res_o;
wire csa_2_4_car_o;
wire csa_2_5_res_o;
wire csa_2_5_car_o;
wire csa_2_6_res_o;
wire csa_2_6_car_o;
wire csa_2_7_res_o;
wire csa_2_7_car_o;
wire csa_2_8_res_o;
wire csa_2_8_car_o;
wire csa_2_9_res_o;
wire csa_2_9_car_o;
wire csa_2_10_res_o;
wire csa_2_10_car_o;
wire csa_2_11_res_o;
wire csa_2_11_car_o;
wire csa_2_12_res_o;
wire csa_2_12_car_o;
wire csa_2_13_res_o;
wire csa_2_13_car_o;
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_0 (
  .opA_i(base_i[0][0])
  ,.opB_i(base_i[1][0])
  ,.opC_i(sign_modification_i[0])
  ,.res_o(csa_0_0_res_o)
  ,.car_o(csa_0_0_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_1 (
  .opA_i(base_i[0][1])
  ,.opB_i(base_i[1][1])
  ,.opC_i(0)
  ,.res_o(csa_0_1_res_o)
  ,.car_o(csa_0_1_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_2 (
  .opA_i(base_i[0][2])
  ,.opB_i(base_i[1][2])
  ,.opC_i(psum_i[0][0])
  ,.res_o(csa_0_2_res_o)
  ,.car_o(csa_0_2_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_3 (
  .opA_i(base_i[0][3])
  ,.opB_i(base_i[1][3])
  ,.opC_i(psum_i[0][1])
  ,.res_o(csa_0_3_res_o)
  ,.car_o(csa_0_3_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_4 (
  .opA_i(base_i[0][4])
  ,.opB_i(base_i[1][4])
  ,.opC_i(psum_i[0][2])
  ,.res_o(csa_0_4_res_o)
  ,.car_o(csa_0_4_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_5 (
  .opA_i(psum_i[1][0])
  ,.opB_i(sign_modification_i[2])
  ,.opC_i(0)
  ,.res_o(csa_0_5_res_o)
  ,.car_o(csa_0_5_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_6 (
  .opA_i(base_i[0][5])
  ,.opB_i(base_i[1][5])
  ,.opC_i(psum_i[0][3])
  ,.res_o(csa_0_6_res_o)
  ,.car_o(csa_0_6_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_7 (
  .opA_i(base_i[0][6])
  ,.opB_i(base_i[1][6])
  ,.opC_i(psum_i[0][4])
  ,.res_o(csa_0_7_res_o)
  ,.car_o(csa_0_7_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_8 (
  .opA_i(psum_i[1][2])
  ,.opB_i(psum_i[2][0])
  ,.opC_i(sign_modification_i[3])
  ,.res_o(csa_0_8_res_o)
  ,.car_o(csa_0_8_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_9 (
  .opA_i(base_i[0][7])
  ,.opB_i(base_i[1][7])
  ,.opC_i(psum_i[0][5])
  ,.res_o(csa_0_9_res_o)
  ,.car_o(csa_0_9_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_10 (
  .opA_i(psum_i[1][3])
  ,.opB_i(psum_i[2][1])
  ,.opC_i(0)
  ,.res_o(csa_0_10_res_o)
  ,.car_o(csa_0_10_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_11 (
  .opA_i(base_i[0][8])
  ,.opB_i(base_i[1][8])
  ,.opC_i(psum_i[0][6])
  ,.res_o(csa_0_11_res_o)
  ,.car_o(csa_0_11_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_12 (
  .opA_i(psum_i[1][4])
  ,.opB_i(psum_i[2][2])
  ,.opC_i(psum_i[3][0])
  ,.res_o(csa_0_12_res_o)
  ,.car_o(csa_0_12_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_13 (
  .opA_i(base_i[0][9])
  ,.opB_i(base_i[1][9])
  ,.opC_i(psum_i[0][7])
  ,.res_o(csa_0_13_res_o)
  ,.car_o(csa_0_13_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_14 (
  .opA_i(psum_i[1][5])
  ,.opB_i(psum_i[2][3])
  ,.opC_i(psum_i[3][1])
  ,.res_o(csa_0_14_res_o)
  ,.car_o(csa_0_14_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_15 (
  .opA_i(base_i[0][10])
  ,.opB_i(base_i[1][10])
  ,.opC_i(psum_i[0][8])
  ,.res_o(csa_0_15_res_o)
  ,.car_o(csa_0_15_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_16 (
  .opA_i(psum_i[1][6])
  ,.opB_i(psum_i[2][4])
  ,.opC_i(psum_i[3][2])
  ,.res_o(csa_0_16_res_o)
  ,.car_o(csa_0_16_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_17 (
  .opA_i(base_i[0][11])
  ,.opB_i(base_i[1][11])
  ,.opC_i(psum_i[0][9])
  ,.res_o(csa_0_17_res_o)
  ,.car_o(csa_0_17_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_18 (
  .opA_i(psum_i[1][7])
  ,.opB_i(psum_i[2][5])
  ,.opC_i(psum_i[3][3])
  ,.res_o(csa_0_18_res_o)
  ,.car_o(csa_0_18_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_19 (
  .opA_i(psum_i[0][10])
  ,.opB_i(psum_i[1][8])
  ,.opC_i(psum_i[2][6])
  ,.res_o(csa_0_19_res_o)
  ,.car_o(csa_0_19_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_20 (
  .opA_i(psum_i[1][9])
  ,.opB_i(psum_i[2][7])
  ,.opC_i(psum_i[3][5])
  ,.res_o(csa_0_20_res_o)
  ,.car_o(csa_0_20_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_21 (
  .opA_i(psum_i[1][10])
  ,.opB_i(psum_i[2][8])
  ,.opC_i(psum_i[3][6])
  ,.res_o(csa_0_21_res_o)
  ,.car_o(csa_0_21_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_22 (
  .opA_i(psum_i[2][9])
  ,.opB_i(psum_i[3][7])
  ,.opC_i(0)
  ,.res_o(csa_0_22_res_o)
  ,.car_o(csa_0_22_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_0 (
  .opA_i(csa_0_1_res_o)
  ,.opB_i(csa_0_0_car_o)
  ,.opC_i(0)
  ,.res_o(csa_1_0_res_o)
  ,.car_o(csa_1_0_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_1 (
  .opA_i(sign_modification_i[1])
  ,.opB_i(csa_0_2_res_o)
  ,.opC_i(csa_0_1_car_o)
  ,.res_o(csa_1_1_res_o)
  ,.car_o(csa_1_1_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_2 (
  .opA_i(csa_0_3_res_o)
  ,.opB_i(csa_0_2_car_o)
  ,.opC_i(0)
  ,.res_o(csa_1_2_res_o)
  ,.car_o(csa_1_2_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_3 (
  .opA_i(csa_0_4_res_o)
  ,.opB_i(csa_0_5_res_o)
  ,.opC_i(csa_0_3_car_o)
  ,.res_o(csa_1_3_res_o)
  ,.car_o(csa_1_3_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_4 (
  .opA_i(psum_i[1][1])
  ,.opB_i(csa_0_6_res_o)
  ,.opC_i(csa_0_4_car_o)
  ,.res_o(csa_1_4_res_o)
  ,.car_o(csa_1_4_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_5 (
  .opA_i(csa_0_7_res_o)
  ,.opB_i(csa_0_8_res_o)
  ,.opC_i(csa_0_6_car_o)
  ,.res_o(csa_1_5_res_o)
  ,.car_o(csa_1_5_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_6 (
  .opA_i(csa_0_9_res_o)
  ,.opB_i(csa_0_10_res_o)
  ,.opC_i(csa_0_7_car_o)
  ,.res_o(csa_1_6_res_o)
  ,.car_o(csa_1_6_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_7 (
  .opA_i(csa_0_11_res_o)
  ,.opB_i(csa_0_12_res_o)
  ,.opC_i(csa_0_9_car_o)
  ,.res_o(csa_1_7_res_o)
  ,.car_o(csa_1_7_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_8 (
  .opA_i(csa_0_13_res_o)
  ,.opB_i(csa_0_14_res_o)
  ,.opC_i(csa_0_11_car_o)
  ,.res_o(csa_1_8_res_o)
  ,.car_o(csa_1_8_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_9 (
  .opA_i(csa_0_15_res_o)
  ,.opB_i(csa_0_16_res_o)
  ,.opC_i(csa_0_13_car_o)
  ,.res_o(csa_1_9_res_o)
  ,.car_o(csa_1_9_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_10 (
  .opA_i(csa_0_17_res_o)
  ,.opB_i(csa_0_18_res_o)
  ,.opC_i(csa_0_15_car_o)
  ,.res_o(csa_1_10_res_o)
  ,.car_o(csa_1_10_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_11 (
  .opA_i(psum_i[3][4])
  ,.opB_i(csa_0_19_res_o)
  ,.opC_i(csa_0_17_car_o)
  ,.res_o(csa_1_11_res_o)
  ,.car_o(csa_1_11_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_12 (
  .opA_i(csa_0_20_res_o)
  ,.opB_i(csa_0_19_car_o)
  ,.opC_i(0)
  ,.res_o(csa_1_12_res_o)
  ,.car_o(csa_1_12_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_13 (
  .opA_i(csa_0_21_res_o)
  ,.opB_i(csa_0_20_car_o)
  ,.opC_i(0)
  ,.res_o(csa_1_13_res_o)
  ,.car_o(csa_1_13_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_14 (
  .opA_i(csa_0_22_res_o)
  ,.opB_i(csa_0_21_car_o)
  ,.opC_i(0)
  ,.res_o(csa_1_14_res_o)
  ,.car_o(csa_1_14_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_0 (
  .opA_i(csa_1_1_res_o)
  ,.opB_i(csa_1_0_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_0_res_o)
  ,.car_o(csa_2_0_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_1 (
  .opA_i(csa_1_2_res_o)
  ,.opB_i(csa_1_1_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_1_res_o)
  ,.car_o(csa_2_1_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_2 (
  .opA_i(csa_1_3_res_o)
  ,.opB_i(csa_1_2_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_2_res_o)
  ,.car_o(csa_2_2_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_3 (
  .opA_i(csa_0_5_car_o)
  ,.opB_i(csa_1_4_res_o)
  ,.opC_i(csa_1_3_car_o)
  ,.res_o(csa_2_3_res_o)
  ,.car_o(csa_2_3_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_4 (
  .opA_i(csa_1_5_res_o)
  ,.opB_i(csa_1_4_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_4_res_o)
  ,.car_o(csa_2_4_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_5 (
  .opA_i(csa_0_8_car_o)
  ,.opB_i(csa_1_6_res_o)
  ,.opC_i(csa_1_5_car_o)
  ,.res_o(csa_2_5_res_o)
  ,.car_o(csa_2_5_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_6 (
  .opA_i(csa_0_10_car_o)
  ,.opB_i(csa_1_7_res_o)
  ,.opC_i(csa_1_6_car_o)
  ,.res_o(csa_2_6_res_o)
  ,.car_o(csa_2_6_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_7 (
  .opA_i(csa_0_12_car_o)
  ,.opB_i(csa_1_8_res_o)
  ,.opC_i(csa_1_7_car_o)
  ,.res_o(csa_2_7_res_o)
  ,.car_o(csa_2_7_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_8 (
  .opA_i(csa_0_14_car_o)
  ,.opB_i(csa_1_9_res_o)
  ,.opC_i(csa_1_8_car_o)
  ,.res_o(csa_2_8_res_o)
  ,.car_o(csa_2_8_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_9 (
  .opA_i(csa_0_16_car_o)
  ,.opB_i(csa_1_10_res_o)
  ,.opC_i(csa_1_9_car_o)
  ,.res_o(csa_2_9_res_o)
  ,.car_o(csa_2_9_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_10 (
  .opA_i(csa_0_18_car_o)
  ,.opB_i(csa_1_11_res_o)
  ,.opC_i(csa_1_10_car_o)
  ,.res_o(csa_2_10_res_o)
  ,.car_o(csa_2_10_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_11 (
  .opA_i(csa_1_12_res_o)
  ,.opB_i(csa_1_11_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_11_res_o)
  ,.car_o(csa_2_11_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_12 (
  .opA_i(csa_1_13_res_o)
  ,.opB_i(csa_1_12_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_12_res_o)
  ,.car_o(csa_2_12_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_13 (
  .opA_i(csa_1_14_res_o)
  ,.opB_i(csa_1_13_car_o)
  ,.opC_i(0)
  ,.res_o(csa_2_13_res_o)
  ,.car_o(csa_2_13_car_o)
);

assign outA_o[0] = csa_0_0_res_o;
assign outB_o[0] = '0;
assign outA_o[1] = csa_1_0_res_o;
assign outB_o[1] = '0;
assign outA_o[2] = csa_2_0_res_o;
assign outB_o[2] = '0;
assign outA_o[3] = csa_2_1_res_o;
assign outB_o[3] = csa_2_0_car_o;
assign outA_o[4] = csa_2_2_res_o;
assign outB_o[4] = csa_2_1_car_o;
assign outA_o[5] = csa_2_3_res_o;
assign outB_o[5] = csa_2_2_car_o;
assign outA_o[6] = csa_2_4_res_o;
assign outB_o[6] = csa_2_3_car_o;
assign outA_o[7] = csa_2_5_res_o;
assign outB_o[7] = csa_2_4_car_o;
assign outA_o[8] = csa_2_6_res_o;
assign outB_o[8] = csa_2_5_car_o;
assign outA_o[9] = csa_2_7_res_o;
assign outB_o[9] = csa_2_6_car_o;
assign outA_o[10] = csa_2_8_res_o;
assign outB_o[10] = csa_2_7_car_o;
assign outA_o[11] = csa_2_9_res_o;
assign outB_o[11] = csa_2_8_car_o;
assign outA_o[12] = csa_2_10_res_o;
assign outB_o[12] = csa_2_9_car_o;
assign outA_o[13] = csa_2_11_res_o;
assign outB_o[13] = csa_2_10_car_o;
assign outA_o[14] = csa_2_12_res_o;
assign outB_o[14] = csa_2_11_car_o;
assign outA_o[15] = csa_2_13_res_o;
assign outB_o[15] = csa_2_12_car_o;
endmodule
