// This file is generated by bsg_multiplier_compressor.py 32 8. Do not modify.
module bsg_multiplier_compressor_32_8
(
  input [1:0][35:0] base_i
  ,input [3:0][34:0] psum_i
  ,input [3:0] sign_modification_i
  ,output [43:0] outA_o
  ,output [43:0] outB_o
);
wire csa_0_0_res_o;
wire csa_0_0_car_o;
wire csa_0_1_res_o;
wire csa_0_1_car_o;
wire csa_0_2_res_o;
wire csa_0_2_car_o;
wire csa_0_3_res_o;
wire csa_0_3_car_o;
wire csa_0_4_res_o;
wire csa_0_4_car_o;
wire csa_0_5_res_o;
wire csa_0_5_car_o;
wire csa_0_6_res_o;
wire csa_0_6_car_o;
wire csa_0_7_res_o;
wire csa_0_7_car_o;
wire csa_0_8_res_o;
wire csa_0_8_car_o;
wire csa_0_9_res_o;
wire csa_0_9_car_o;
wire csa_0_10_res_o;
wire csa_0_10_car_o;
wire csa_0_11_res_o;
wire csa_0_11_car_o;
wire csa_0_12_res_o;
wire csa_0_12_car_o;
wire csa_0_13_res_o;
wire csa_0_13_car_o;
wire csa_0_14_res_o;
wire csa_0_14_car_o;
wire csa_0_15_res_o;
wire csa_0_15_car_o;
wire csa_0_16_res_o;
wire csa_0_16_car_o;
wire csa_0_17_res_o;
wire csa_0_17_car_o;
wire csa_0_18_res_o;
wire csa_0_18_car_o;
wire csa_0_19_res_o;
wire csa_0_19_car_o;
wire csa_0_20_res_o;
wire csa_0_20_car_o;
wire csa_0_21_res_o;
wire csa_0_21_car_o;
wire csa_0_22_res_o;
wire csa_0_22_car_o;
wire csa_0_23_res_o;
wire csa_0_23_car_o;
wire csa_0_24_res_o;
wire csa_0_24_car_o;
wire csa_0_25_res_o;
wire csa_0_25_car_o;
wire csa_0_26_res_o;
wire csa_0_26_car_o;
wire csa_0_27_res_o;
wire csa_0_27_car_o;
wire csa_0_28_res_o;
wire csa_0_28_car_o;
wire csa_0_29_res_o;
wire csa_0_29_car_o;
wire csa_0_30_res_o;
wire csa_0_30_car_o;
wire csa_0_31_res_o;
wire csa_0_31_car_o;
wire csa_0_32_res_o;
wire csa_0_32_car_o;
wire csa_0_33_res_o;
wire csa_0_33_car_o;
wire csa_0_34_res_o;
wire csa_0_34_car_o;
wire csa_0_35_res_o;
wire csa_0_35_car_o;
wire csa_0_36_res_o;
wire csa_0_36_car_o;
wire csa_0_37_res_o;
wire csa_0_37_car_o;
wire csa_0_38_res_o;
wire csa_0_38_car_o;
wire csa_0_39_res_o;
wire csa_0_39_car_o;
wire csa_0_40_res_o;
wire csa_0_40_car_o;
wire csa_0_41_res_o;
wire csa_0_41_car_o;
wire csa_0_42_res_o;
wire csa_0_42_car_o;
wire csa_0_43_res_o;
wire csa_0_43_car_o;
wire csa_0_44_res_o;
wire csa_0_44_car_o;
wire csa_0_45_res_o;
wire csa_0_45_car_o;
wire csa_0_46_res_o;
wire csa_0_46_car_o;
wire csa_0_47_res_o;
wire csa_0_47_car_o;
wire csa_0_48_res_o;
wire csa_0_48_car_o;
wire csa_0_49_res_o;
wire csa_0_49_car_o;
wire csa_0_50_res_o;
wire csa_0_50_car_o;
wire csa_0_51_res_o;
wire csa_0_51_car_o;
wire csa_0_52_res_o;
wire csa_0_52_car_o;
wire csa_0_53_res_o;
wire csa_0_53_car_o;
wire csa_0_54_res_o;
wire csa_0_54_car_o;
wire csa_0_55_res_o;
wire csa_0_55_car_o;
wire csa_0_56_res_o;
wire csa_0_56_car_o;
wire csa_0_57_res_o;
wire csa_0_57_car_o;
wire csa_0_58_res_o;
wire csa_0_58_car_o;
wire csa_0_59_res_o;
wire csa_0_59_car_o;
wire csa_0_60_res_o;
wire csa_0_60_car_o;
wire csa_0_61_res_o;
wire csa_0_61_car_o;
wire csa_0_62_res_o;
wire csa_0_62_car_o;
wire csa_0_63_res_o;
wire csa_0_63_car_o;
wire csa_0_64_res_o;
wire csa_0_64_car_o;
wire csa_0_65_res_o;
wire csa_0_65_car_o;
wire csa_0_66_res_o;
wire csa_0_66_car_o;
wire csa_1_0_res_o;
wire csa_1_0_car_o;
wire csa_1_1_res_o;
wire csa_1_1_car_o;
wire csa_1_2_res_o;
wire csa_1_2_car_o;
wire csa_1_3_res_o;
wire csa_1_3_car_o;
wire csa_1_4_res_o;
wire csa_1_4_car_o;
wire csa_1_5_res_o;
wire csa_1_5_car_o;
wire csa_1_6_res_o;
wire csa_1_6_car_o;
wire csa_1_7_res_o;
wire csa_1_7_car_o;
wire csa_1_8_res_o;
wire csa_1_8_car_o;
wire csa_1_9_res_o;
wire csa_1_9_car_o;
wire csa_1_10_res_o;
wire csa_1_10_car_o;
wire csa_1_11_res_o;
wire csa_1_11_car_o;
wire csa_1_12_res_o;
wire csa_1_12_car_o;
wire csa_1_13_res_o;
wire csa_1_13_car_o;
wire csa_1_14_res_o;
wire csa_1_14_car_o;
wire csa_1_15_res_o;
wire csa_1_15_car_o;
wire csa_1_16_res_o;
wire csa_1_16_car_o;
wire csa_1_17_res_o;
wire csa_1_17_car_o;
wire csa_1_18_res_o;
wire csa_1_18_car_o;
wire csa_1_19_res_o;
wire csa_1_19_car_o;
wire csa_1_20_res_o;
wire csa_1_20_car_o;
wire csa_1_21_res_o;
wire csa_1_21_car_o;
wire csa_1_22_res_o;
wire csa_1_22_car_o;
wire csa_1_23_res_o;
wire csa_1_23_car_o;
wire csa_1_24_res_o;
wire csa_1_24_car_o;
wire csa_1_25_res_o;
wire csa_1_25_car_o;
wire csa_1_26_res_o;
wire csa_1_26_car_o;
wire csa_1_27_res_o;
wire csa_1_27_car_o;
wire csa_1_28_res_o;
wire csa_1_28_car_o;
wire csa_1_29_res_o;
wire csa_1_29_car_o;
wire csa_1_30_res_o;
wire csa_1_30_car_o;
wire csa_1_31_res_o;
wire csa_1_31_car_o;
wire csa_1_32_res_o;
wire csa_1_32_car_o;
wire csa_1_33_res_o;
wire csa_1_33_car_o;
wire csa_1_34_res_o;
wire csa_1_34_car_o;
wire csa_1_35_res_o;
wire csa_1_35_car_o;
wire csa_1_36_res_o;
wire csa_1_36_car_o;
wire csa_1_37_res_o;
wire csa_1_37_car_o;
wire csa_1_38_res_o;
wire csa_1_38_car_o;
wire csa_1_39_res_o;
wire csa_1_39_car_o;
wire csa_1_40_res_o;
wire csa_1_40_car_o;
wire csa_2_0_res_o;
wire csa_2_0_car_o;
wire csa_2_1_res_o;
wire csa_2_1_car_o;
wire csa_2_2_res_o;
wire csa_2_2_car_o;
wire csa_2_3_res_o;
wire csa_2_3_car_o;
wire csa_2_4_res_o;
wire csa_2_4_car_o;
wire csa_2_5_res_o;
wire csa_2_5_car_o;
wire csa_2_6_res_o;
wire csa_2_6_car_o;
wire csa_2_7_res_o;
wire csa_2_7_car_o;
wire csa_2_8_res_o;
wire csa_2_8_car_o;
wire csa_2_9_res_o;
wire csa_2_9_car_o;
wire csa_2_10_res_o;
wire csa_2_10_car_o;
wire csa_2_11_res_o;
wire csa_2_11_car_o;
wire csa_2_12_res_o;
wire csa_2_12_car_o;
wire csa_2_13_res_o;
wire csa_2_13_car_o;
wire csa_2_14_res_o;
wire csa_2_14_car_o;
wire csa_2_15_res_o;
wire csa_2_15_car_o;
wire csa_2_16_res_o;
wire csa_2_16_car_o;
wire csa_2_17_res_o;
wire csa_2_17_car_o;
wire csa_2_18_res_o;
wire csa_2_18_car_o;
wire csa_2_19_res_o;
wire csa_2_19_car_o;
wire csa_2_20_res_o;
wire csa_2_20_car_o;
wire csa_2_21_res_o;
wire csa_2_21_car_o;
wire csa_2_22_res_o;
wire csa_2_22_car_o;
wire csa_2_23_res_o;
wire csa_2_23_car_o;
wire csa_2_24_res_o;
wire csa_2_24_car_o;
wire csa_2_25_res_o;
wire csa_2_25_car_o;
wire csa_2_26_res_o;
wire csa_2_26_car_o;
wire csa_2_27_res_o;
wire csa_2_27_car_o;
wire csa_2_28_res_o;
wire csa_2_28_car_o;
wire csa_2_29_res_o;
wire csa_2_29_car_o;
wire csa_2_30_res_o;
wire csa_2_30_car_o;
wire csa_2_31_res_o;
wire csa_2_31_car_o;
wire csa_2_32_res_o;
wire csa_2_32_car_o;
wire csa_2_33_res_o;
wire csa_2_33_car_o;
wire csa_2_34_res_o;
wire csa_2_34_car_o;
wire csa_2_35_res_o;
wire csa_2_35_car_o;
wire csa_2_36_res_o;
wire csa_2_36_car_o;
wire csa_2_37_res_o;
wire csa_2_37_car_o;
wire csa_2_38_res_o;
wire csa_2_38_car_o;
wire csa_2_39_res_o;
wire csa_2_39_car_o;
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_0 (
  .opA_i(base_i[0][0])
  ,.opB_i(base_i[1][0])
  ,.opC_i(sign_modification_i[0])
  ,.res_o(csa_0_0_res_o)
  ,.car_o(csa_0_0_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_1 (
  .opA_i(base_i[0][2])
  ,.opB_i(base_i[1][2])
  ,.opC_i(psum_i[0][0])
  ,.res_o(csa_0_1_res_o)
  ,.car_o(csa_0_1_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_2 (
  .opA_i(base_i[0][3])
  ,.opB_i(base_i[1][3])
  ,.opC_i(psum_i[0][1])
  ,.res_o(csa_0_2_res_o)
  ,.car_o(csa_0_2_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_3 (
  .opA_i(base_i[0][4])
  ,.opB_i(base_i[1][4])
  ,.opC_i(psum_i[0][2])
  ,.res_o(csa_0_3_res_o)
  ,.car_o(csa_0_3_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_4 (
  .opA_i(base_i[0][5])
  ,.opB_i(base_i[1][5])
  ,.opC_i(psum_i[0][3])
  ,.res_o(csa_0_4_res_o)
  ,.car_o(csa_0_4_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_5 (
  .opA_i(base_i[0][6])
  ,.opB_i(base_i[1][6])
  ,.opC_i(psum_i[0][4])
  ,.res_o(csa_0_5_res_o)
  ,.car_o(csa_0_5_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_6 (
  .opA_i(psum_i[1][2])
  ,.opB_i(psum_i[2][0])
  ,.opC_i(sign_modification_i[3])
  ,.res_o(csa_0_6_res_o)
  ,.car_o(csa_0_6_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_7 (
  .opA_i(base_i[0][7])
  ,.opB_i(base_i[1][7])
  ,.opC_i(psum_i[0][5])
  ,.res_o(csa_0_7_res_o)
  ,.car_o(csa_0_7_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_8 (
  .opA_i(base_i[0][8])
  ,.opB_i(base_i[1][8])
  ,.opC_i(psum_i[0][6])
  ,.res_o(csa_0_8_res_o)
  ,.car_o(csa_0_8_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_9 (
  .opA_i(psum_i[1][4])
  ,.opB_i(psum_i[2][2])
  ,.opC_i(psum_i[3][0])
  ,.res_o(csa_0_9_res_o)
  ,.car_o(csa_0_9_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_10 (
  .opA_i(base_i[0][9])
  ,.opB_i(base_i[1][9])
  ,.opC_i(psum_i[0][7])
  ,.res_o(csa_0_10_res_o)
  ,.car_o(csa_0_10_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_11 (
  .opA_i(psum_i[1][5])
  ,.opB_i(psum_i[2][3])
  ,.opC_i(psum_i[3][1])
  ,.res_o(csa_0_11_res_o)
  ,.car_o(csa_0_11_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_12 (
  .opA_i(base_i[0][10])
  ,.opB_i(base_i[1][10])
  ,.opC_i(psum_i[0][8])
  ,.res_o(csa_0_12_res_o)
  ,.car_o(csa_0_12_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_13 (
  .opA_i(psum_i[1][6])
  ,.opB_i(psum_i[2][4])
  ,.opC_i(psum_i[3][2])
  ,.res_o(csa_0_13_res_o)
  ,.car_o(csa_0_13_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_14 (
  .opA_i(base_i[0][11])
  ,.opB_i(base_i[1][11])
  ,.opC_i(psum_i[0][9])
  ,.res_o(csa_0_14_res_o)
  ,.car_o(csa_0_14_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_15 (
  .opA_i(psum_i[1][7])
  ,.opB_i(psum_i[2][5])
  ,.opC_i(psum_i[3][3])
  ,.res_o(csa_0_15_res_o)
  ,.car_o(csa_0_15_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_16 (
  .opA_i(base_i[0][12])
  ,.opB_i(base_i[1][12])
  ,.opC_i(psum_i[0][10])
  ,.res_o(csa_0_16_res_o)
  ,.car_o(csa_0_16_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_17 (
  .opA_i(psum_i[1][8])
  ,.opB_i(psum_i[2][6])
  ,.opC_i(psum_i[3][4])
  ,.res_o(csa_0_17_res_o)
  ,.car_o(csa_0_17_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_18 (
  .opA_i(base_i[0][13])
  ,.opB_i(base_i[1][13])
  ,.opC_i(psum_i[0][11])
  ,.res_o(csa_0_18_res_o)
  ,.car_o(csa_0_18_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_19 (
  .opA_i(psum_i[1][9])
  ,.opB_i(psum_i[2][7])
  ,.opC_i(psum_i[3][5])
  ,.res_o(csa_0_19_res_o)
  ,.car_o(csa_0_19_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_20 (
  .opA_i(base_i[0][14])
  ,.opB_i(base_i[1][14])
  ,.opC_i(psum_i[0][12])
  ,.res_o(csa_0_20_res_o)
  ,.car_o(csa_0_20_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_21 (
  .opA_i(psum_i[1][10])
  ,.opB_i(psum_i[2][8])
  ,.opC_i(psum_i[3][6])
  ,.res_o(csa_0_21_res_o)
  ,.car_o(csa_0_21_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_22 (
  .opA_i(base_i[0][15])
  ,.opB_i(base_i[1][15])
  ,.opC_i(psum_i[0][13])
  ,.res_o(csa_0_22_res_o)
  ,.car_o(csa_0_22_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_23 (
  .opA_i(psum_i[1][11])
  ,.opB_i(psum_i[2][9])
  ,.opC_i(psum_i[3][7])
  ,.res_o(csa_0_23_res_o)
  ,.car_o(csa_0_23_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_24 (
  .opA_i(base_i[0][16])
  ,.opB_i(base_i[1][16])
  ,.opC_i(psum_i[0][14])
  ,.res_o(csa_0_24_res_o)
  ,.car_o(csa_0_24_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_25 (
  .opA_i(psum_i[1][12])
  ,.opB_i(psum_i[2][10])
  ,.opC_i(psum_i[3][8])
  ,.res_o(csa_0_25_res_o)
  ,.car_o(csa_0_25_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_26 (
  .opA_i(base_i[0][17])
  ,.opB_i(base_i[1][17])
  ,.opC_i(psum_i[0][15])
  ,.res_o(csa_0_26_res_o)
  ,.car_o(csa_0_26_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_27 (
  .opA_i(psum_i[1][13])
  ,.opB_i(psum_i[2][11])
  ,.opC_i(psum_i[3][9])
  ,.res_o(csa_0_27_res_o)
  ,.car_o(csa_0_27_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_28 (
  .opA_i(base_i[0][18])
  ,.opB_i(base_i[1][18])
  ,.opC_i(psum_i[0][16])
  ,.res_o(csa_0_28_res_o)
  ,.car_o(csa_0_28_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_29 (
  .opA_i(psum_i[1][14])
  ,.opB_i(psum_i[2][12])
  ,.opC_i(psum_i[3][10])
  ,.res_o(csa_0_29_res_o)
  ,.car_o(csa_0_29_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_30 (
  .opA_i(base_i[0][19])
  ,.opB_i(base_i[1][19])
  ,.opC_i(psum_i[0][17])
  ,.res_o(csa_0_30_res_o)
  ,.car_o(csa_0_30_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_31 (
  .opA_i(psum_i[1][15])
  ,.opB_i(psum_i[2][13])
  ,.opC_i(psum_i[3][11])
  ,.res_o(csa_0_31_res_o)
  ,.car_o(csa_0_31_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_32 (
  .opA_i(base_i[0][20])
  ,.opB_i(base_i[1][20])
  ,.opC_i(psum_i[0][18])
  ,.res_o(csa_0_32_res_o)
  ,.car_o(csa_0_32_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_33 (
  .opA_i(psum_i[1][16])
  ,.opB_i(psum_i[2][14])
  ,.opC_i(psum_i[3][12])
  ,.res_o(csa_0_33_res_o)
  ,.car_o(csa_0_33_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_34 (
  .opA_i(base_i[0][21])
  ,.opB_i(base_i[1][21])
  ,.opC_i(psum_i[0][19])
  ,.res_o(csa_0_34_res_o)
  ,.car_o(csa_0_34_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_35 (
  .opA_i(psum_i[1][17])
  ,.opB_i(psum_i[2][15])
  ,.opC_i(psum_i[3][13])
  ,.res_o(csa_0_35_res_o)
  ,.car_o(csa_0_35_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_36 (
  .opA_i(base_i[0][22])
  ,.opB_i(base_i[1][22])
  ,.opC_i(psum_i[0][20])
  ,.res_o(csa_0_36_res_o)
  ,.car_o(csa_0_36_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_37 (
  .opA_i(psum_i[1][18])
  ,.opB_i(psum_i[2][16])
  ,.opC_i(psum_i[3][14])
  ,.res_o(csa_0_37_res_o)
  ,.car_o(csa_0_37_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_38 (
  .opA_i(base_i[0][23])
  ,.opB_i(base_i[1][23])
  ,.opC_i(psum_i[0][21])
  ,.res_o(csa_0_38_res_o)
  ,.car_o(csa_0_38_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_39 (
  .opA_i(psum_i[1][19])
  ,.opB_i(psum_i[2][17])
  ,.opC_i(psum_i[3][15])
  ,.res_o(csa_0_39_res_o)
  ,.car_o(csa_0_39_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_40 (
  .opA_i(base_i[0][24])
  ,.opB_i(base_i[1][24])
  ,.opC_i(psum_i[0][22])
  ,.res_o(csa_0_40_res_o)
  ,.car_o(csa_0_40_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_41 (
  .opA_i(psum_i[1][20])
  ,.opB_i(psum_i[2][18])
  ,.opC_i(psum_i[3][16])
  ,.res_o(csa_0_41_res_o)
  ,.car_o(csa_0_41_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_42 (
  .opA_i(base_i[0][25])
  ,.opB_i(base_i[1][25])
  ,.opC_i(psum_i[0][23])
  ,.res_o(csa_0_42_res_o)
  ,.car_o(csa_0_42_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_43 (
  .opA_i(psum_i[1][21])
  ,.opB_i(psum_i[2][19])
  ,.opC_i(psum_i[3][17])
  ,.res_o(csa_0_43_res_o)
  ,.car_o(csa_0_43_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_44 (
  .opA_i(base_i[0][26])
  ,.opB_i(base_i[1][26])
  ,.opC_i(psum_i[0][24])
  ,.res_o(csa_0_44_res_o)
  ,.car_o(csa_0_44_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_45 (
  .opA_i(psum_i[1][22])
  ,.opB_i(psum_i[2][20])
  ,.opC_i(psum_i[3][18])
  ,.res_o(csa_0_45_res_o)
  ,.car_o(csa_0_45_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_46 (
  .opA_i(base_i[0][27])
  ,.opB_i(base_i[1][27])
  ,.opC_i(psum_i[0][25])
  ,.res_o(csa_0_46_res_o)
  ,.car_o(csa_0_46_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_47 (
  .opA_i(psum_i[1][23])
  ,.opB_i(psum_i[2][21])
  ,.opC_i(psum_i[3][19])
  ,.res_o(csa_0_47_res_o)
  ,.car_o(csa_0_47_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_48 (
  .opA_i(base_i[0][28])
  ,.opB_i(base_i[1][28])
  ,.opC_i(psum_i[0][26])
  ,.res_o(csa_0_48_res_o)
  ,.car_o(csa_0_48_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_49 (
  .opA_i(psum_i[1][24])
  ,.opB_i(psum_i[2][22])
  ,.opC_i(psum_i[3][20])
  ,.res_o(csa_0_49_res_o)
  ,.car_o(csa_0_49_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_50 (
  .opA_i(base_i[0][29])
  ,.opB_i(base_i[1][29])
  ,.opC_i(psum_i[0][27])
  ,.res_o(csa_0_50_res_o)
  ,.car_o(csa_0_50_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_51 (
  .opA_i(psum_i[1][25])
  ,.opB_i(psum_i[2][23])
  ,.opC_i(psum_i[3][21])
  ,.res_o(csa_0_51_res_o)
  ,.car_o(csa_0_51_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_52 (
  .opA_i(base_i[0][30])
  ,.opB_i(base_i[1][30])
  ,.opC_i(psum_i[0][28])
  ,.res_o(csa_0_52_res_o)
  ,.car_o(csa_0_52_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_53 (
  .opA_i(psum_i[1][26])
  ,.opB_i(psum_i[2][24])
  ,.opC_i(psum_i[3][22])
  ,.res_o(csa_0_53_res_o)
  ,.car_o(csa_0_53_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_54 (
  .opA_i(base_i[0][31])
  ,.opB_i(base_i[1][31])
  ,.opC_i(psum_i[0][29])
  ,.res_o(csa_0_54_res_o)
  ,.car_o(csa_0_54_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_55 (
  .opA_i(psum_i[1][27])
  ,.opB_i(psum_i[2][25])
  ,.opC_i(psum_i[3][23])
  ,.res_o(csa_0_55_res_o)
  ,.car_o(csa_0_55_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_56 (
  .opA_i(base_i[0][32])
  ,.opB_i(base_i[1][32])
  ,.opC_i(psum_i[0][30])
  ,.res_o(csa_0_56_res_o)
  ,.car_o(csa_0_56_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_57 (
  .opA_i(psum_i[1][28])
  ,.opB_i(psum_i[2][26])
  ,.opC_i(psum_i[3][24])
  ,.res_o(csa_0_57_res_o)
  ,.car_o(csa_0_57_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_58 (
  .opA_i(base_i[0][33])
  ,.opB_i(base_i[1][33])
  ,.opC_i(psum_i[0][31])
  ,.res_o(csa_0_58_res_o)
  ,.car_o(csa_0_58_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_59 (
  .opA_i(psum_i[1][29])
  ,.opB_i(psum_i[2][27])
  ,.opC_i(psum_i[3][25])
  ,.res_o(csa_0_59_res_o)
  ,.car_o(csa_0_59_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_60 (
  .opA_i(base_i[0][34])
  ,.opB_i(base_i[1][34])
  ,.opC_i(psum_i[0][32])
  ,.res_o(csa_0_60_res_o)
  ,.car_o(csa_0_60_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_61 (
  .opA_i(psum_i[1][30])
  ,.opB_i(psum_i[2][28])
  ,.opC_i(psum_i[3][26])
  ,.res_o(csa_0_61_res_o)
  ,.car_o(csa_0_61_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_62 (
  .opA_i(base_i[0][35])
  ,.opB_i(base_i[1][35])
  ,.opC_i(psum_i[0][33])
  ,.res_o(csa_0_62_res_o)
  ,.car_o(csa_0_62_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_63 (
  .opA_i(psum_i[1][31])
  ,.opB_i(psum_i[2][29])
  ,.opC_i(psum_i[3][27])
  ,.res_o(csa_0_63_res_o)
  ,.car_o(csa_0_63_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_64 (
  .opA_i(psum_i[0][34])
  ,.opB_i(psum_i[1][32])
  ,.opC_i(psum_i[2][30])
  ,.res_o(csa_0_64_res_o)
  ,.car_o(csa_0_64_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_65 (
  .opA_i(psum_i[1][33])
  ,.opB_i(psum_i[2][31])
  ,.opC_i(psum_i[3][29])
  ,.res_o(csa_0_65_res_o)
  ,.car_o(csa_0_65_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_0_66 (
  .opA_i(psum_i[1][34])
  ,.opB_i(psum_i[2][32])
  ,.opC_i(psum_i[3][30])
  ,.res_o(csa_0_66_res_o)
  ,.car_o(csa_0_66_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_0 (
  .opA_i(base_i[0][1])
  ,.opB_i(base_i[1][1])
  ,.opC_i(csa_0_0_car_o)
  ,.res_o(csa_1_0_res_o)
  ,.car_o(csa_1_0_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_1 (
  .opA_i(sign_modification_i[1])
  ,.opB_i(csa_0_1_res_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_1_1_res_o)
  ,.car_o(csa_1_1_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_2 (
  .opA_i(csa_0_2_res_o)
  ,.opB_i(csa_0_1_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_1_2_res_o)
  ,.car_o(csa_1_2_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_3 (
  .opA_i(psum_i[1][0])
  ,.opB_i(sign_modification_i[2])
  ,.opC_i(csa_0_3_res_o)
  ,.res_o(csa_1_3_res_o)
  ,.car_o(csa_1_3_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_4 (
  .opA_i(psum_i[1][1])
  ,.opB_i(csa_0_4_res_o)
  ,.opC_i(csa_0_3_car_o)
  ,.res_o(csa_1_4_res_o)
  ,.car_o(csa_1_4_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_5 (
  .opA_i(csa_0_5_res_o)
  ,.opB_i(csa_0_6_res_o)
  ,.opC_i(csa_0_4_car_o)
  ,.res_o(csa_1_5_res_o)
  ,.car_o(csa_1_5_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_6 (
  .opA_i(psum_i[1][3])
  ,.opB_i(psum_i[2][1])
  ,.opC_i(csa_0_7_res_o)
  ,.res_o(csa_1_6_res_o)
  ,.car_o(csa_1_6_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_7 (
  .opA_i(csa_0_5_car_o)
  ,.opB_i(csa_0_6_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_1_7_res_o)
  ,.car_o(csa_1_7_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_8 (
  .opA_i(csa_0_8_res_o)
  ,.opB_i(csa_0_9_res_o)
  ,.opC_i(csa_0_7_car_o)
  ,.res_o(csa_1_8_res_o)
  ,.car_o(csa_1_8_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_9 (
  .opA_i(csa_0_10_res_o)
  ,.opB_i(csa_0_11_res_o)
  ,.opC_i(csa_0_8_car_o)
  ,.res_o(csa_1_9_res_o)
  ,.car_o(csa_1_9_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_10 (
  .opA_i(csa_0_12_res_o)
  ,.opB_i(csa_0_13_res_o)
  ,.opC_i(csa_0_10_car_o)
  ,.res_o(csa_1_10_res_o)
  ,.car_o(csa_1_10_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_11 (
  .opA_i(csa_0_14_res_o)
  ,.opB_i(csa_0_15_res_o)
  ,.opC_i(csa_0_12_car_o)
  ,.res_o(csa_1_11_res_o)
  ,.car_o(csa_1_11_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_12 (
  .opA_i(csa_0_16_res_o)
  ,.opB_i(csa_0_17_res_o)
  ,.opC_i(csa_0_14_car_o)
  ,.res_o(csa_1_12_res_o)
  ,.car_o(csa_1_12_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_13 (
  .opA_i(csa_0_18_res_o)
  ,.opB_i(csa_0_19_res_o)
  ,.opC_i(csa_0_16_car_o)
  ,.res_o(csa_1_13_res_o)
  ,.car_o(csa_1_13_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_14 (
  .opA_i(csa_0_20_res_o)
  ,.opB_i(csa_0_21_res_o)
  ,.opC_i(csa_0_18_car_o)
  ,.res_o(csa_1_14_res_o)
  ,.car_o(csa_1_14_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_15 (
  .opA_i(csa_0_22_res_o)
  ,.opB_i(csa_0_23_res_o)
  ,.opC_i(csa_0_20_car_o)
  ,.res_o(csa_1_15_res_o)
  ,.car_o(csa_1_15_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_16 (
  .opA_i(csa_0_24_res_o)
  ,.opB_i(csa_0_25_res_o)
  ,.opC_i(csa_0_22_car_o)
  ,.res_o(csa_1_16_res_o)
  ,.car_o(csa_1_16_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_17 (
  .opA_i(csa_0_26_res_o)
  ,.opB_i(csa_0_27_res_o)
  ,.opC_i(csa_0_24_car_o)
  ,.res_o(csa_1_17_res_o)
  ,.car_o(csa_1_17_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_18 (
  .opA_i(csa_0_28_res_o)
  ,.opB_i(csa_0_29_res_o)
  ,.opC_i(csa_0_26_car_o)
  ,.res_o(csa_1_18_res_o)
  ,.car_o(csa_1_18_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_19 (
  .opA_i(csa_0_30_res_o)
  ,.opB_i(csa_0_31_res_o)
  ,.opC_i(csa_0_28_car_o)
  ,.res_o(csa_1_19_res_o)
  ,.car_o(csa_1_19_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_20 (
  .opA_i(csa_0_32_res_o)
  ,.opB_i(csa_0_33_res_o)
  ,.opC_i(csa_0_30_car_o)
  ,.res_o(csa_1_20_res_o)
  ,.car_o(csa_1_20_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_21 (
  .opA_i(csa_0_34_res_o)
  ,.opB_i(csa_0_35_res_o)
  ,.opC_i(csa_0_32_car_o)
  ,.res_o(csa_1_21_res_o)
  ,.car_o(csa_1_21_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_22 (
  .opA_i(csa_0_36_res_o)
  ,.opB_i(csa_0_37_res_o)
  ,.opC_i(csa_0_34_car_o)
  ,.res_o(csa_1_22_res_o)
  ,.car_o(csa_1_22_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_23 (
  .opA_i(csa_0_38_res_o)
  ,.opB_i(csa_0_39_res_o)
  ,.opC_i(csa_0_36_car_o)
  ,.res_o(csa_1_23_res_o)
  ,.car_o(csa_1_23_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_24 (
  .opA_i(csa_0_40_res_o)
  ,.opB_i(csa_0_41_res_o)
  ,.opC_i(csa_0_38_car_o)
  ,.res_o(csa_1_24_res_o)
  ,.car_o(csa_1_24_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_25 (
  .opA_i(csa_0_42_res_o)
  ,.opB_i(csa_0_43_res_o)
  ,.opC_i(csa_0_40_car_o)
  ,.res_o(csa_1_25_res_o)
  ,.car_o(csa_1_25_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_26 (
  .opA_i(csa_0_44_res_o)
  ,.opB_i(csa_0_45_res_o)
  ,.opC_i(csa_0_42_car_o)
  ,.res_o(csa_1_26_res_o)
  ,.car_o(csa_1_26_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_27 (
  .opA_i(csa_0_46_res_o)
  ,.opB_i(csa_0_47_res_o)
  ,.opC_i(csa_0_44_car_o)
  ,.res_o(csa_1_27_res_o)
  ,.car_o(csa_1_27_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_28 (
  .opA_i(csa_0_48_res_o)
  ,.opB_i(csa_0_49_res_o)
  ,.opC_i(csa_0_46_car_o)
  ,.res_o(csa_1_28_res_o)
  ,.car_o(csa_1_28_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_29 (
  .opA_i(csa_0_50_res_o)
  ,.opB_i(csa_0_51_res_o)
  ,.opC_i(csa_0_48_car_o)
  ,.res_o(csa_1_29_res_o)
  ,.car_o(csa_1_29_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_30 (
  .opA_i(csa_0_52_res_o)
  ,.opB_i(csa_0_53_res_o)
  ,.opC_i(csa_0_50_car_o)
  ,.res_o(csa_1_30_res_o)
  ,.car_o(csa_1_30_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_31 (
  .opA_i(csa_0_54_res_o)
  ,.opB_i(csa_0_55_res_o)
  ,.opC_i(csa_0_52_car_o)
  ,.res_o(csa_1_31_res_o)
  ,.car_o(csa_1_31_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_32 (
  .opA_i(csa_0_56_res_o)
  ,.opB_i(csa_0_57_res_o)
  ,.opC_i(csa_0_54_car_o)
  ,.res_o(csa_1_32_res_o)
  ,.car_o(csa_1_32_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_33 (
  .opA_i(csa_0_58_res_o)
  ,.opB_i(csa_0_59_res_o)
  ,.opC_i(csa_0_56_car_o)
  ,.res_o(csa_1_33_res_o)
  ,.car_o(csa_1_33_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_34 (
  .opA_i(csa_0_60_res_o)
  ,.opB_i(csa_0_61_res_o)
  ,.opC_i(csa_0_58_car_o)
  ,.res_o(csa_1_34_res_o)
  ,.car_o(csa_1_34_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_35 (
  .opA_i(csa_0_62_res_o)
  ,.opB_i(csa_0_63_res_o)
  ,.opC_i(csa_0_60_car_o)
  ,.res_o(csa_1_35_res_o)
  ,.car_o(csa_1_35_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_36 (
  .opA_i(psum_i[3][28])
  ,.opB_i(csa_0_64_res_o)
  ,.opC_i(csa_0_62_car_o)
  ,.res_o(csa_1_36_res_o)
  ,.car_o(csa_1_36_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_37 (
  .opA_i(csa_0_65_res_o)
  ,.opB_i(csa_0_64_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_1_37_res_o)
  ,.car_o(csa_1_37_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_38 (
  .opA_i(csa_0_66_res_o)
  ,.opB_i(csa_0_65_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_1_38_res_o)
  ,.car_o(csa_1_38_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_39 (
  .opA_i(psum_i[2][33])
  ,.opB_i(psum_i[3][31])
  ,.opC_i(csa_0_66_car_o)
  ,.res_o(csa_1_39_res_o)
  ,.car_o(csa_1_39_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_1_40 (
  .opA_i(psum_i[2][34])
  ,.opB_i(psum_i[3][32])
  ,.opC_i(1'b0)
  ,.res_o(csa_1_40_res_o)
  ,.car_o(csa_1_40_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_0 (
  .opA_i(csa_1_1_res_o)
  ,.opB_i(csa_1_0_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_0_res_o)
  ,.car_o(csa_2_0_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_1 (
  .opA_i(csa_1_2_res_o)
  ,.opB_i(csa_1_1_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_1_res_o)
  ,.car_o(csa_2_1_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_2 (
  .opA_i(csa_0_2_car_o)
  ,.opB_i(csa_1_3_res_o)
  ,.opC_i(csa_1_2_car_o)
  ,.res_o(csa_2_2_res_o)
  ,.car_o(csa_2_2_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_3 (
  .opA_i(csa_1_4_res_o)
  ,.opB_i(csa_1_3_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_3_res_o)
  ,.car_o(csa_2_3_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_4 (
  .opA_i(csa_1_5_res_o)
  ,.opB_i(csa_1_4_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_4_res_o)
  ,.car_o(csa_2_4_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_5 (
  .opA_i(csa_1_6_res_o)
  ,.opB_i(csa_1_7_res_o)
  ,.opC_i(csa_1_5_car_o)
  ,.res_o(csa_2_5_res_o)
  ,.car_o(csa_2_5_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_6 (
  .opA_i(csa_1_8_res_o)
  ,.opB_i(csa_1_6_car_o)
  ,.opC_i(csa_1_7_car_o)
  ,.res_o(csa_2_6_res_o)
  ,.car_o(csa_2_6_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_7 (
  .opA_i(csa_0_9_car_o)
  ,.opB_i(csa_1_9_res_o)
  ,.opC_i(csa_1_8_car_o)
  ,.res_o(csa_2_7_res_o)
  ,.car_o(csa_2_7_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_8 (
  .opA_i(csa_0_11_car_o)
  ,.opB_i(csa_1_10_res_o)
  ,.opC_i(csa_1_9_car_o)
  ,.res_o(csa_2_8_res_o)
  ,.car_o(csa_2_8_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_9 (
  .opA_i(csa_0_13_car_o)
  ,.opB_i(csa_1_11_res_o)
  ,.opC_i(csa_1_10_car_o)
  ,.res_o(csa_2_9_res_o)
  ,.car_o(csa_2_9_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_10 (
  .opA_i(csa_0_15_car_o)
  ,.opB_i(csa_1_12_res_o)
  ,.opC_i(csa_1_11_car_o)
  ,.res_o(csa_2_10_res_o)
  ,.car_o(csa_2_10_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_11 (
  .opA_i(csa_0_17_car_o)
  ,.opB_i(csa_1_13_res_o)
  ,.opC_i(csa_1_12_car_o)
  ,.res_o(csa_2_11_res_o)
  ,.car_o(csa_2_11_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_12 (
  .opA_i(csa_0_19_car_o)
  ,.opB_i(csa_1_14_res_o)
  ,.opC_i(csa_1_13_car_o)
  ,.res_o(csa_2_12_res_o)
  ,.car_o(csa_2_12_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_13 (
  .opA_i(csa_0_21_car_o)
  ,.opB_i(csa_1_15_res_o)
  ,.opC_i(csa_1_14_car_o)
  ,.res_o(csa_2_13_res_o)
  ,.car_o(csa_2_13_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_14 (
  .opA_i(csa_0_23_car_o)
  ,.opB_i(csa_1_16_res_o)
  ,.opC_i(csa_1_15_car_o)
  ,.res_o(csa_2_14_res_o)
  ,.car_o(csa_2_14_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_15 (
  .opA_i(csa_0_25_car_o)
  ,.opB_i(csa_1_17_res_o)
  ,.opC_i(csa_1_16_car_o)
  ,.res_o(csa_2_15_res_o)
  ,.car_o(csa_2_15_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_16 (
  .opA_i(csa_0_27_car_o)
  ,.opB_i(csa_1_18_res_o)
  ,.opC_i(csa_1_17_car_o)
  ,.res_o(csa_2_16_res_o)
  ,.car_o(csa_2_16_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_17 (
  .opA_i(csa_0_29_car_o)
  ,.opB_i(csa_1_19_res_o)
  ,.opC_i(csa_1_18_car_o)
  ,.res_o(csa_2_17_res_o)
  ,.car_o(csa_2_17_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_18 (
  .opA_i(csa_0_31_car_o)
  ,.opB_i(csa_1_20_res_o)
  ,.opC_i(csa_1_19_car_o)
  ,.res_o(csa_2_18_res_o)
  ,.car_o(csa_2_18_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_19 (
  .opA_i(csa_0_33_car_o)
  ,.opB_i(csa_1_21_res_o)
  ,.opC_i(csa_1_20_car_o)
  ,.res_o(csa_2_19_res_o)
  ,.car_o(csa_2_19_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_20 (
  .opA_i(csa_0_35_car_o)
  ,.opB_i(csa_1_22_res_o)
  ,.opC_i(csa_1_21_car_o)
  ,.res_o(csa_2_20_res_o)
  ,.car_o(csa_2_20_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_21 (
  .opA_i(csa_0_37_car_o)
  ,.opB_i(csa_1_23_res_o)
  ,.opC_i(csa_1_22_car_o)
  ,.res_o(csa_2_21_res_o)
  ,.car_o(csa_2_21_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_22 (
  .opA_i(csa_0_39_car_o)
  ,.opB_i(csa_1_24_res_o)
  ,.opC_i(csa_1_23_car_o)
  ,.res_o(csa_2_22_res_o)
  ,.car_o(csa_2_22_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_23 (
  .opA_i(csa_0_41_car_o)
  ,.opB_i(csa_1_25_res_o)
  ,.opC_i(csa_1_24_car_o)
  ,.res_o(csa_2_23_res_o)
  ,.car_o(csa_2_23_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_24 (
  .opA_i(csa_0_43_car_o)
  ,.opB_i(csa_1_26_res_o)
  ,.opC_i(csa_1_25_car_o)
  ,.res_o(csa_2_24_res_o)
  ,.car_o(csa_2_24_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_25 (
  .opA_i(csa_0_45_car_o)
  ,.opB_i(csa_1_27_res_o)
  ,.opC_i(csa_1_26_car_o)
  ,.res_o(csa_2_25_res_o)
  ,.car_o(csa_2_25_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_26 (
  .opA_i(csa_0_47_car_o)
  ,.opB_i(csa_1_28_res_o)
  ,.opC_i(csa_1_27_car_o)
  ,.res_o(csa_2_26_res_o)
  ,.car_o(csa_2_26_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_27 (
  .opA_i(csa_0_49_car_o)
  ,.opB_i(csa_1_29_res_o)
  ,.opC_i(csa_1_28_car_o)
  ,.res_o(csa_2_27_res_o)
  ,.car_o(csa_2_27_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_28 (
  .opA_i(csa_0_51_car_o)
  ,.opB_i(csa_1_30_res_o)
  ,.opC_i(csa_1_29_car_o)
  ,.res_o(csa_2_28_res_o)
  ,.car_o(csa_2_28_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_29 (
  .opA_i(csa_0_53_car_o)
  ,.opB_i(csa_1_31_res_o)
  ,.opC_i(csa_1_30_car_o)
  ,.res_o(csa_2_29_res_o)
  ,.car_o(csa_2_29_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_30 (
  .opA_i(csa_0_55_car_o)
  ,.opB_i(csa_1_32_res_o)
  ,.opC_i(csa_1_31_car_o)
  ,.res_o(csa_2_30_res_o)
  ,.car_o(csa_2_30_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_31 (
  .opA_i(csa_0_57_car_o)
  ,.opB_i(csa_1_33_res_o)
  ,.opC_i(csa_1_32_car_o)
  ,.res_o(csa_2_31_res_o)
  ,.car_o(csa_2_31_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_32 (
  .opA_i(csa_0_59_car_o)
  ,.opB_i(csa_1_34_res_o)
  ,.opC_i(csa_1_33_car_o)
  ,.res_o(csa_2_32_res_o)
  ,.car_o(csa_2_32_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_33 (
  .opA_i(csa_0_61_car_o)
  ,.opB_i(csa_1_35_res_o)
  ,.opC_i(csa_1_34_car_o)
  ,.res_o(csa_2_33_res_o)
  ,.car_o(csa_2_33_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_34 (
  .opA_i(csa_0_63_car_o)
  ,.opB_i(csa_1_36_res_o)
  ,.opC_i(csa_1_35_car_o)
  ,.res_o(csa_2_34_res_o)
  ,.car_o(csa_2_34_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_35 (
  .opA_i(csa_1_37_res_o)
  ,.opB_i(csa_1_36_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_35_res_o)
  ,.car_o(csa_2_35_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_36 (
  .opA_i(csa_1_38_res_o)
  ,.opB_i(csa_1_37_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_36_res_o)
  ,.car_o(csa_2_36_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_37 (
  .opA_i(csa_1_39_res_o)
  ,.opB_i(csa_1_38_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_37_res_o)
  ,.car_o(csa_2_37_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_38 (
  .opA_i(csa_1_40_res_o)
  ,.opB_i(csa_1_39_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_38_res_o)
  ,.car_o(csa_2_38_car_o)
);
bsg_adder_carry_save#(
  .width_p(1)
) csa_2_39 (
  .opA_i(psum_i[3][33])
  ,.opB_i(csa_1_40_car_o)
  ,.opC_i(1'b0)
  ,.res_o(csa_2_39_res_o)
  ,.car_o(csa_2_39_car_o)
);

assign outA_o[0] = csa_0_0_res_o;
assign outB_o[0] = '0;
assign outA_o[1] = csa_1_0_res_o;
assign outB_o[1] = '0;
assign outA_o[2] = csa_2_0_res_o;
assign outB_o[2] = '0;
assign outA_o[3] = csa_2_1_res_o;
assign outB_o[3] = csa_2_0_car_o;
assign outA_o[4] = csa_2_2_res_o;
assign outB_o[4] = csa_2_1_car_o;
assign outA_o[5] = csa_2_3_res_o;
assign outB_o[5] = csa_2_2_car_o;
assign outA_o[6] = csa_2_4_res_o;
assign outB_o[6] = csa_2_3_car_o;
assign outA_o[7] = csa_2_5_res_o;
assign outB_o[7] = csa_2_4_car_o;
assign outA_o[8] = csa_2_6_res_o;
assign outB_o[8] = csa_2_5_car_o;
assign outA_o[9] = csa_2_7_res_o;
assign outB_o[9] = csa_2_6_car_o;
assign outA_o[10] = csa_2_8_res_o;
assign outB_o[10] = csa_2_7_car_o;
assign outA_o[11] = csa_2_9_res_o;
assign outB_o[11] = csa_2_8_car_o;
assign outA_o[12] = csa_2_10_res_o;
assign outB_o[12] = csa_2_9_car_o;
assign outA_o[13] = csa_2_11_res_o;
assign outB_o[13] = csa_2_10_car_o;
assign outA_o[14] = csa_2_12_res_o;
assign outB_o[14] = csa_2_11_car_o;
assign outA_o[15] = csa_2_13_res_o;
assign outB_o[15] = csa_2_12_car_o;
assign outA_o[16] = csa_2_14_res_o;
assign outB_o[16] = csa_2_13_car_o;
assign outA_o[17] = csa_2_15_res_o;
assign outB_o[17] = csa_2_14_car_o;
assign outA_o[18] = csa_2_16_res_o;
assign outB_o[18] = csa_2_15_car_o;
assign outA_o[19] = csa_2_17_res_o;
assign outB_o[19] = csa_2_16_car_o;
assign outA_o[20] = csa_2_18_res_o;
assign outB_o[20] = csa_2_17_car_o;
assign outA_o[21] = csa_2_19_res_o;
assign outB_o[21] = csa_2_18_car_o;
assign outA_o[22] = csa_2_20_res_o;
assign outB_o[22] = csa_2_19_car_o;
assign outA_o[23] = csa_2_21_res_o;
assign outB_o[23] = csa_2_20_car_o;
assign outA_o[24] = csa_2_22_res_o;
assign outB_o[24] = csa_2_21_car_o;
assign outA_o[25] = csa_2_23_res_o;
assign outB_o[25] = csa_2_22_car_o;
assign outA_o[26] = csa_2_24_res_o;
assign outB_o[26] = csa_2_23_car_o;
assign outA_o[27] = csa_2_25_res_o;
assign outB_o[27] = csa_2_24_car_o;
assign outA_o[28] = csa_2_26_res_o;
assign outB_o[28] = csa_2_25_car_o;
assign outA_o[29] = csa_2_27_res_o;
assign outB_o[29] = csa_2_26_car_o;
assign outA_o[30] = csa_2_28_res_o;
assign outB_o[30] = csa_2_27_car_o;
assign outA_o[31] = csa_2_29_res_o;
assign outB_o[31] = csa_2_28_car_o;
assign outA_o[32] = csa_2_30_res_o;
assign outB_o[32] = csa_2_29_car_o;
assign outA_o[33] = csa_2_31_res_o;
assign outB_o[33] = csa_2_30_car_o;
assign outA_o[34] = csa_2_32_res_o;
assign outB_o[34] = csa_2_31_car_o;
assign outA_o[35] = csa_2_33_res_o;
assign outB_o[35] = csa_2_32_car_o;
assign outA_o[36] = csa_2_34_res_o;
assign outB_o[36] = csa_2_33_car_o;
assign outA_o[37] = csa_2_35_res_o;
assign outB_o[37] = csa_2_34_car_o;
assign outA_o[38] = csa_2_36_res_o;
assign outB_o[38] = csa_2_35_car_o;
assign outA_o[39] = csa_2_37_res_o;
assign outB_o[39] = csa_2_36_car_o;
assign outA_o[40] = csa_2_38_res_o;
assign outB_o[40] = csa_2_37_car_o;
assign outA_o[41] = csa_2_39_res_o;
assign outB_o[41] = csa_2_38_car_o;
assign outA_o[42] = psum_i[3][34];
assign outB_o[42] = csa_2_39_car_o;
assign outA_o[43] = '0;
assign outB_o[43] = '0;
endmodule
