
// ## AUTOGENERATED; DO NOT MODIFY
// ## num_rows_p = 8
// ## num_cols_p = 8
// ## num_dly_p = 8


module bsg_rp_clk_gen_osc_v3_row
 (input    async_reset_neg_i
  , input  async_set_neg_i
  , input  clkgate_i
  , input  clkdly_i
  , input  clkfb_i
  , input  ctl_i
  , output clk_o
  );

  wire lobit, hibit;
  sky130_fd_sc_hd__conb_1 T0 (.HI(hibit), .LO(lobit));

  wire ctl_r;
  sky130_fd_sc_hd__dfbbp_1 D0 (.Q(ctl_r), .Q_N(), .CLK(clkgate_i), .D(ctl_i), .RESET_B(async_reset_neg_i), .SET_B(async_set_neg_i));
  wire ctl_en;
  sky130_fd_sc_hd__nand2_1 N0 (.Y(ctl_en), .A(clkdly_i), .B(ctl_r));

  wire fb;
  sky130_fd_sc_hd__nand2_1 N1 (.Y(fb), .A(clkfb_i), .B(hibit));
  wire clk;
  sky130_fd_sc_hd__nand2_1 N2 (.Y(clk), .A(fb), .B(ctl_en));

  assign #50ps clk_o = clk;

endmodule


module bsg_rp_clk_gen_osc_v3_col
  (input async_reset_i
   , input clkgate_i
   , input clkdly_i
   , input clkfb_i
   , input [8-1:0] ctl_one_hot_i
   , output clk_o
   );

  wire lobit, hibit;
  sky130_fd_sc_hd__conb_1 T0 (.HI(hibit), .LO(lobit));

  // Size to 1/4 of column load 
  wire clkgate_inv;
  sky130_fd_sc_hd__inv_1 I0 (.Y(clkgate_inv), .A(clkgate_i));

  wire clkdly_inv;
  sky130_fd_sc_hd__inv_1 I1 (.Y(clkdly_inv), .A(clkdly_i));

  wire async_reset_neg;
  sky130_fd_sc_hd__inv_1 I2 (.Y(async_reset_neg), .A(async_reset_i));

  wire [8:0] clkfb;
  assign clkfb[0] = clkfb_i;

  wire [8-1:0] async_reset_neg_li, async_set_neg_li;


      assign async_reset_neg_li[0] = hibit;
      assign async_set_neg_li[0]   = async_reset_neg;
    

      bsg_rp_clk_gen_osc_v3_row row_0_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[0])
         ,.async_set_neg_i(async_set_neg_li[0])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[0])
         ,.ctl_i(ctl_one_hot_i[0])
         ,.clk_o(clkfb[1])
         );


      assign async_reset_neg_li[1] = async_reset_neg;
      assign async_set_neg_li[1]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_1_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[1])
         ,.async_set_neg_i(async_set_neg_li[1])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[1])
         ,.ctl_i(ctl_one_hot_i[1])
         ,.clk_o(clkfb[2])
         );


      assign async_reset_neg_li[2] = async_reset_neg;
      assign async_set_neg_li[2]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_2_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[2])
         ,.async_set_neg_i(async_set_neg_li[2])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[2])
         ,.ctl_i(ctl_one_hot_i[2])
         ,.clk_o(clkfb[3])
         );


      assign async_reset_neg_li[3] = async_reset_neg;
      assign async_set_neg_li[3]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_3_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[3])
         ,.async_set_neg_i(async_set_neg_li[3])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[3])
         ,.ctl_i(ctl_one_hot_i[3])
         ,.clk_o(clkfb[4])
         );


      assign async_reset_neg_li[4] = async_reset_neg;
      assign async_set_neg_li[4]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_4_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[4])
         ,.async_set_neg_i(async_set_neg_li[4])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[4])
         ,.ctl_i(ctl_one_hot_i[4])
         ,.clk_o(clkfb[5])
         );


      assign async_reset_neg_li[5] = async_reset_neg;
      assign async_set_neg_li[5]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_5_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[5])
         ,.async_set_neg_i(async_set_neg_li[5])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[5])
         ,.ctl_i(ctl_one_hot_i[5])
         ,.clk_o(clkfb[6])
         );


      assign async_reset_neg_li[6] = async_reset_neg;
      assign async_set_neg_li[6]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_6_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[6])
         ,.async_set_neg_i(async_set_neg_li[6])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[6])
         ,.ctl_i(ctl_one_hot_i[6])
         ,.clk_o(clkfb[7])
         );


      assign async_reset_neg_li[7] = async_reset_neg;
      assign async_set_neg_li[7]   = hibit;
    

      bsg_rp_clk_gen_osc_v3_row row_7_BSG_DONT_TOUCH
        (.async_reset_neg_i(async_reset_neg_li[7])
         ,.async_set_neg_i(async_set_neg_li[7])
         ,.clkgate_i(clkgate_inv)
         ,.clkdly_i(clkdly_inv)
         ,.clkfb_i(clkfb[7])
         ,.ctl_i(ctl_one_hot_i[7])
         ,.clk_o(clkfb[8])
         );


  assign clk_o = clkfb[8];

endmodule

