
// ## AUTOGENERATED; DO NOT MODIFY
// ## num_rows_p = 2
// ## num_cols_p = 2
// ## num_dly_p = 2


module bsg_rp_clk_gen_osc_v3
  (input async_reset_i
   , input trigger_i
   , input [3:0] ctl_one_hot_i
   , output clk_o
   );
  wire lobit;
  TIELBWP7T30P140ULVT T0 (.ZN(lobit));
  wire hibit;
  TIEHBWP7T30P140ULVT T1 (.Z(hibit));
  wire async_reset_neg;
  INVD1BWP7T30P140ULVT I0 (.ZN(async_reset_neg), .I(async_reset_i));
  wire fb_inv, fb, fb_dly, fb_rst;
  CKND1BWP7T30P140ULVT I1 (.ZN(fb_inv), .I(fb));
  CKND2D1BWP7T30P140ULVT N0 (.ZN(fb_rst), .A1(fb_inv), .A2(async_reset_neg));
  wire [2:0] n;
  assign n[0] = fb_rst;


    CKBD4BWP7T30P140ULVT B0 (.Z(n[1]), .I(n[0]));


    CKBD4BWP7T30P140ULVT B1 (.Z(n[2]), .I(n[1]));


  // Delay value ignored in synthesis
  assign #100 fb_dly = n[2];
  CKND4BWP7T30P140ULVT I2 (.ZN(clk_o), .I(fb_dly));
  wire fb_gate;
  CKND1BWP7T30P140ULVT I3 (.ZN(fb_gate), .I(fb_dly));
  wire gate_en_sync_1_r, gate_en_sync_2_r;
  DFQD1BWP7T30P140ULVT S1 (.D(trigger_i), .CP(fb_gate), .Q(gate_en_sync_1_r));
  DFQD1BWP7T30P140ULVT S2 (.D(gate_en_sync_1_r), .CP(fb_gate), .Q(gate_en_sync_2_r));
  wire fb_gated;
  // Size to 1/4 of number of taps
  CKLNQD16BWP7T30P140ULVT CG0 (.Q(fb_gated), .CP(fb_gate), .E(gate_en_sync_2_r), .TE(lobit));
  wire [2:0] fb_col;
  assign fb_col[0] = 1'b0;


      bsg_rp_clk_gen_osc_v3_col col_0_BSG_DONT_TOUCH
       (.async_reset_i(async_reset_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(fb_dly)
        ,.clkfb_i(fb_col[0])
        ,.ctl_one_hot_i(ctl_one_hot_i[1:0])
        ,.clk_o(fb_col[1])
        );


      bsg_rp_clk_gen_osc_v3_col col_1_BSG_DONT_TOUCH
       (.async_reset_i(async_reset_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(fb_dly)
        ,.clkfb_i(fb_col[1])
        ,.ctl_one_hot_i(ctl_one_hot_i[3:2])
        ,.clk_o(fb_col[2])
        );


  assign fb = fb_col[2];
endmodule

