#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned long RP;
typedef unsigned long RO;
typedef unsigned long long ULL;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef struct {
    U  I674;
    RP  I675;
} RmaReceiveClock1;
typedef NodeCount  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef unsigned long long TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I694;
    unsigned long long I695;
    unsigned  I696[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I703;
    E_fn  I704;
    struct iptmpl * I705;
    unsigned I707;
    struct eblk * I708;
} eblk_struct;
typedef struct {
    RP  I703;
    RP  I704;
    RP  I705;
    unsigned I707;
    RP  I708;
} RmaEblk;
typedef union {
    double I694;
    unsigned long long I695;
    unsigned  I696[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I744;
    RmaEblk  I702;
    U  I745;
    US  I746 :1;
    US  I747 :4;
    US  I183 :2;
    US  state :2;
    US  I749 :1;
    US  I750 :2;
    US  I751 :2;
    US  fHsim :1;
    US  I556 :1;
    scalar  newval;
    scalar  I753;
    RP  I754;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I734;
    scalar  I735;
    scalar  I736;
    scalar  I737;
    scalar  fHsim :1;
    scalar  I183 :6;
    U  I739;
    EBLK  I740;
    void * I741;
    UP   I742[1];
};
struct RmaMPSched {
    RP  I734;
    scalar  I735;
    scalar  I736;
    scalar  I737;
    scalar  fHsim :1;
    scalar  I183 :6;
    U  I739;
    RmaEblk  I740;
    RP  I741;
    RP   I742[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I734;
    scalar  I735;
    scalar  I736;
    scalar  I737;
    scalar  I183;
    U  I739;
    RmaEblk  I740;
    scalar  I751;
    scalar  I758;
    scalar  I759;
    scalar  I760;
    U  I761;
    RmaClockStruct  I762;
    RmaClockStruct  I763;
    U  state;
    U  I764;
    RP  I705;
    RP  I765;
    RP  I766;
    RP   I742[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I768;
    void * I769;
};
typedef struct {
    RmaEblk  I702;
    RP  I770;
    scalar  I771;
    scalar  I751;
    scalar  I772;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I734;
    scalar  I735;
    scalar  I736;
    scalar  I737;
    scalar  fHsim :1;
    scalar  I183 :6;
    U  I739;
    RmaEblk  I740;
    scalar  I751;
    scalar  I758;
    scalar  I759;
    scalar  I760;
    U  state :4;
    U  I774 :28;
    RmaClockStruct  I762;
    RmaClockStruct  I763;
    RP  I775;
    RP  I705;
    RP  I776;
    RP   I742[1];
};
typedef struct red_t {
    U  I777;
    U  I778;
    U  I657;
} RED;
typedef struct predd {
    PD_e  I183;
    RED   I779[0];
} PREDD;
union rhs_value {
    vec32  I780;
    scalar  I771;
    vec32  * I751;
    double I781;
    U  I782;
};
typedef struct nbs_t {
    struct nbs_t * I783;
    struct nbs_t * I785;
    void (* I786)(struct nbs_t * I787);
    unsigned I788 :1;
    unsigned I789 :1;
    unsigned I790 :1;
    unsigned I791 :1;
    unsigned I792 :27;
    U  I793;
    void * I794;
    union rhs_value I795;
    vec32  I694;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I797;
} NBS;
typedef struct {
    RP  I798;
    RP  I765;
    RP  I705;
    RP  I766;
    RmaEblk  I702;
    RmaEblk  I799;
    RP  I800;
    scalar  I771;
    scalar  I751;
    char state;
    uscope_t  I801;
    U  I802;
    RP  I803;
    scalar  I758;
    scalar  I759;
    scalar  I760;
    RmaClockStruct  I762;
    RmaClockStruct  I763;
    RP  I741;
} RmaPulse;
typedef struct {
    int * I804;
    long long I805;
} TypeData;
struct etype {
    U  I572 :8;
    U  I573 :24;
    U  I574;
    U  I575 :1;
    U  I576 :1;
    U  I577 :1;
    U  I578 :1;
    U  I579 :1;
    U  I580 :1;
    U  I581 :1;
    U  I582 :1;
    U  I583 :1;
    U  I584 :4;
    U  I585 :1;
    U  I586 :1;
    U  I587 :1;
    U  I588 :1;
    U  I589 :1;
    U  I590 :1;
    U  I591 :1;
    U  I592 :1;
    U  I593 :2;
    U  I594 :1;
    U  I595 :2;
    U  I596 :1;
    U  I597 :1;
    U  I598 :1;
    U  I599 :1;
    U  I600 :2;
    U  I601;
    TypeData  * I602;
    U  I603;
    U  I604;
    U  I605 :1;
    U  I606 :1;
    U  I607 :1;
    U  I608 :1;
    U  I609 :2;
    U  I610 :2;
    U  I611 :1;
    U  I612 :1;
    U  I613 :1;
    U  I614 :1;
    U  I615 :1;
    U  I616 :1;
    U  I617 :1;
    U  I618 :1;
    U  I619 :16;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I809 :1;
    U  I810 :1;
    U  I811 :1;
    U  I812 :1;
    U  I813 :1;
    U  I814 :1;
    U  I815 :1;
    U  I816 :1;
    U  I817 :1;
    U  I818 :1;
    U  I819 :1;
    U  I820 :1;
    U  I821 :1;
    U  I822 :1;
    U  I823 :1;
    U  I824 :1;
    U  I825 :1;
    U  I826 :1;
    QIRDModuleType  I827 :2;
    U  I828 :1;
    U  I829 :1;
    U  I830 :1;
    U  I831 :1;
    U  I832 :1;
    U  I833 :1;
    U  I834 :1;
    U  I835 :1;
    U  I836 :1;
    U  I837 :1;
    U  I838 :1;
    U  I839 :1;
    U  I840 :1;
    U  I841 :1;
    U  I842 :1;
    U  I843 :1;
    U  I844 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    UP  I38;
    U  I39;
    BitFlags  I40;
    U  I41;
    U  I42;
    U  I43;
    U  I44;
    U  I45;
    U  * I46;
    U  I47;
    U  * I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  I54;
    U  I55;
    U  * I56;
    U  * I57;
    U  I58;
    U  I59;
    U  * I60;
    U  I61;
    U  * I62;
    U  I63;
    U  I64;
    U  I65;
    U  I66;
    U  * I67;
    U  I68;
    U  * I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  I74;
    U  I75;
    U  * I76;
    char * I77;
    U  I78;
    U  I79;
    U  I80;
    U  I81;
    U  I82;
    U  * I83;
    U  I84;
    U  I85;
    UP  * I86;
    U  I87;
    U  I88;
    UP  * I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  I94;
    U  I95;
    U  * I96;
    U  I97;
    U  I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  * I102;
    U  * I103;
    U  I104;
    U  I105;
    struct taskInfo * I106;
    U  I108;
    U  I109;
    int * I110;
    UP  * I111;
    U  * I112;
    U  I113;
    U  I114;
    U  I115;
    U  I116;
    U  I117;
    struct qrefer * I118;
    U  * I120;
    unsigned * I121;
    void * I122;
    U  I123;
    U  I124;
    struct classStaticReferData * I125;
    U  I127;
    U  * I128;
    U  I129;
    struct wakeupInfoStruct * I130;
    U  I132;
    U  I133;
    U  I134;
    U  * I135;
    U  I136;
    U  * I137;
    U  I138;
    U  I139;
    U  I140;
    U  * I141;
    U  I142;
    U  * I143;
    U  I144;
    U  I145;
    U  * I146;
    U  I147;
    U  I148;
    U  * I149;
    U  * I150;
    U  * I151;
    U  I152;
    U  I153;
    U  I154;
    U  I155;
    U  I156;
    struct qrefee * I157;
    U  * I159;
    U  I160;
    struct qdefrefee * I161;
    U  * I163;
    int (* I164)(void);
    char * I165;
    U  I166;
    U  I167;
    void * I168;
    void * I169;
    NumLibs_t  I170;
    char * I171;
    U  * I172;
    U  I173;
    U  I174;
    U  I175;
    U  I176;
    U  I177;
    U  * I178;
    U  * I179;
    int I180;
    struct clock_load * I181;
    int I196;
    struct clock_data * I197;
    int I213;
    struct clock_hiconn * I214;
    U  I218;
    int I219;
    U  I220;
    int I221;
    U  * I222;
    U  * I223;
    U  I224;
    void * I225;
    U  I226;
    U  I227;
    UP  * I228;
    void * I229;
    U  I230;
    UP  * I231;
    U  * I232;
    int (* I233)(void);
    U  * I234;
    UP  * I235;
    U  * I236;
    U  I237 :1;
    U  I238 :31;
    U  I239;
    U  I240;
    UP  * I241;
    U  * I242;
    U  I243 :1;
    U  I244 :1;
    U  I245 :1;
    U  I246 :1;
    U  I247 :28;
    U  I248;
    U  I249;
    U  I250;
    U  I251 :31;
    U  I252 :1;
    UP  * I253;
    UP  * I254;
    U  * I255;
    U  * I256;
    U  * I257;
    UP  * I258;
    UP  * I259;
    UP  * I260;
    U  * I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    UP  * I265;
    char * I266;
    U  I267;
    U  I268;
    U  I269;
    UP  * I270;
    UP  * I271;
    UP  * I272;
    UP  * I273;
    UP  * I274;
    UP  * I275;
    UP  * I276;
    UP  * I277;
    UP  * I278;
    UP  * I279;
    UP  * I280;
    UP  * I281;
    UP  * I282;
    U  * I283;
    U  * I284;
    UP  * I285;
    U  I286;
    U  I287;
    U  I288;
    U  I289;
    U  I290;
    U  I291;
    U  I292;
    U  I293;
    char * I294;
    U  * I295;
    U  I296;
    U  I297;
    U  I298;
    U  I299;
    U  I300;
    UP  * I301;
    UP  * I302;
    UP  * I303;
    UP  * I304;
    struct daidirInfo * I305;
    struct vcs_tftable * I307;
    U  I309;
    UP  * I310;
    UP  * I311;
    U  I312;
    U  I313;
    U  I314;
    UP  * I315;
    U  * I316;
    struct qird_hil_data * I317;
    UP  (* I319)(void);
    UP  (* I320)(void);
    UP  (* I321)(void);
    UP  (* I322)(void);
    UP  (* I323)(void);
    int * I324;
    int (* I325)(void);
    char * I326;
    UP  * I327;
    UP  * I328;
    UP  (* I329)(void);
    int (* I330)(void);
    int * I331;
    int (* I332)(void);
    int * I333;
    char * I334;
    U  * I335;
    U  * I336;
    U  * I337;
    U  * I338;
    void * I339;
    U  I340;
    void * I341;
    U  I342;
    U  I343;
    U  I344;
    U  I345;
    U  I346;
    U  I347;
    UP  * I348;
    U  * I349;
    U  * I350;
    U  I351 :15;
    U  I352 :14;
    U  I353 :1;
    U  I354 :1;
    U  I355 :1;
    U  I356 :3;
    U  I357 :1;
    U  I358 :1;
    U  I359 :17;
    U  I360 :3;
    U  I361 :5;
    U  I362 :2;
    U  I363 :1;
    U  I364 :31;
    struct scope * I365;
    U  I367;
    U  I368;
    U  I369;
    U  * I370;
    U  * I371;
    U  * I372;
    U  I373;
    U  I374;
    U  I375;
    struct pcbt * I376;
    U  I386;
    U  I387;
    U  I388;
    U  I389;
    void * I390;
    void * I391;
    void * I392;
    int I393;
    U  * I394;
    U  I395;
    U  I396;
    U  I397;
    U  I398;
    U  I399;
    U  I400;
    U  I401;
    void * I402;
    UP  * I403;
    U  I404;
    U  I405;
    void * I406;
    U  I407;
    void * I408;
    U  I409;
    void * I410;
    U  I411;
    int (* I412)(void);
    int (* I413)(void);
    void * I414;
    void * I415;
    void * I416;
    U  I417;
    U  I418;
    U  I419;
    U  I420;
    U  I421;
    U  I422;
    char * I423;
    U  I424;
    U  * I425;
    U  I426;
    U  * I427;
    U  I428;
    U  I429;
    U  I430;
    U  I431;
    U  I432;
    U  I433;
    U  * I434;
    U  I435;
    U  I436;
    U  * I437;
    U  I438;
    U  I439;
    U  * I440;
    char * I441;
    U  I442;
    U  I443;
    U  I444;
    U  I445;
    U  * I446;
    U  * I447;
    U  I448;
    U  * I449;
    U  * I450;
    U  I451;
    U  I452;
    U  I453;
    U  I454;
    struct cosim_info * I455;
    U  I457;
    U  * I458;
    U  I459;
    void * I460;
    U  I461;
    U  * I462;
    U  I463;
    U  * I464;
    U  I465;
    U  I466;
    U  * I467;
    U  I468;
    U  * I469;
    U  I470;
    U  * I471;
    U  I472;
    U  I473;
    U  I474;
    U  I475;
    U  I476;
    U  I477;
    U  I478;
    U  I479;
    U  I480;
    U  * I481;
    U  * I482;
    void (* I483)(void);
    U  * I484;
    UP  * I485;
    struct mhdl_outInfo * I486;
    UP  * I488;
    U  I489;
    UP  * I490;
    U  I491;
    void * I492;
    U  * I493;
    void * I494;
    char * I495;
    int (* I496)(void);
    U  * I497;
    char * I498;
    char * I499;
    U  I500;
    U  * I501;
    char * I502;
    U  I503;
    struct regInitInfo * I504;
    UP  * I506;
    U  * I507;
    char * I508;
    U  I509;
    U  I510;
    U  I511;
    U  I512;
    U  I513;
    U  I514;
    U  I515;
    U  I516;
    UP  * I517;
    U  I518;
    U  I519;
    U  I520;
    U  I521;
    UP  * I522;
    U  I523;
    UP  * I524;
    U  I525;
    U  I526;
    U  I527;
    U  * I528;
    U  I529;
    U  I530;
    U  I531;
    U  * I532;
    U  * I533;
    UP  * I534;
    UP  * I535;
    void * I536;
    UP  I537;
    void * I538;
    void * I539;
    void * I540;
    void * I541;
    void * I542;
    UP  I543;
    U  * I544;
    U  * I545;
    void * I546;
    U  I547 :1;
    U  I548 :31;
    U  I549;
    U  I550;
    U  I551;
    int I552;
    U  I553 :1;
    U  I554 :1;
    U  I555 :1;
    U  I556 :29;
    void * I557;
    void * I558;
    void * I559;
    void * I560;
    UP  * I561;
    U  * I562;
    U  I563;
    char * I564;
    U  * I565;
    U  * I566;
    char * I567;
    int * I568;
    UP  * I569;
    struct etype * I570;
    U  I620;
    U  I621;
    U  I622;
    U  * I623;
    void * I624;
    U  I625;
    U  I626;
    void * I627;
    U  I628;
    U  I629;
    U  * I630;
    U  I631;
    U  * I632;
    U  I633;
    U  I634;
    U  * I635;
};
typedef struct pcbt {
    U  * I378;
    UP  I379;
    U  I380;
    U  I381;
    U  I382;
    U  I383;
    U  I384;
    U  I385;
} PCBT;
struct iptmpl {
    QIRD  * I709;
    struct vcs_globals_t * I710;
    void * I712;
    UP  I713;
    UP  I714;
    struct iptmpl * I705[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I895[256];
    struct _hsimPeriodL * I849;
} HsimPeriodL;
typedef struct {
    U   I897[2];
    U  I898 :1;
    U  I899 :1;
    U  I900 :8;
    U  I901 :8;
    U  I902 :8;
    U  I903 :4;
    unsigned long long I904;
    unsigned long long I905;
    unsigned long long I906;
    unsigned long long I907;
    unsigned long long I908;
    U  I909;
    U  I910;
    U  I911;
    U  I912;
    HsimPeriodL  * I913;
    HsimPeriodL  * I914;
    U  I915;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I916;
    InstNum  I917;
    U  I857;
    scalar  I918;
    UB  I919;
    UB  I920;
    UB  I921;
    UB  I922;
    U  I923;
    U  I924;
    U  I925;
    U  I926;
    U  I927;
    U  I928;
    HsimSignalMonitor  * I929;
    RP  I930;
    RmaTimeStamp64  I931;
    U  I932;
    RmaTimeStamp64  I933;
} HsimNodeRecord;
typedef struct {
    RP  I934;
    RP  I705;
} RmaIbfIp;
typedef struct {
    RP  I934;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I702;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I702;
    RP  I935;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I702;
    RP  I936;
    RP  I935;
    vec32  I937;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I702;
    RP  I936;
    RP  I935;
    vec32   I750[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I702;
    RP  I936;
    RP  I935;
    scalar   I938[1];
} RmaAnySchedECg;
typedef struct {
    RP  I939;
} RmaRootCbkCg;
typedef struct {
    RP  I940;
} RmaRootVcdCg;
typedef struct {
    RP  I941;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I702;
    RP  I942;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I698 :30;
    U  I943 :1;
    U  I944 :1;
    vec32  I780;
    U  I945;
    RP  I946;
    RP  I947;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I953;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I640;
    RmaIbfPcode   I953[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I953;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I954;
    U  I955 :3;
    U  I956 :1;
    U  I957 :1;
    U  I958 :16;
} RmaNbaGateOfn;
typedef struct {
    NBS  I959;
    RmaIbfPcode  I954;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I962;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I962;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I963;
    U  * I964;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I965;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I965;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I702;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I702;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I702;
    RP  pcode;
    RP  pfn;
    scalar  I966;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I967;
    RP  I968;
    RP  I969;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I702;
    RP  pcode;
    U  I857;
    U   I691[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I779;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaGateDelay;
typedef struct {
    U  I5;
    RP  I779;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaGateBehavioralDelay;
typedef struct {
    U  I5;
    union {
        RP  I1116;
        RP  I1381;
        RP  I1394;
    } I754;
    RmaIbfPcode  I954;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I970;
    RmaIbfPcode  I954;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I954;
    RmaMps  I971;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I972;
    RmaIbfPcode  I954;
    RmaEblk  I740;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I954;
    RmaMpspNewCsdf  I973;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I973;
    RmaIbfPcode  I954;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I5;
    RP  I657;
    RmaTransEventHdr  I863;
    RP  I776;
    RmaIbfPcode  I954;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I5;
    U  I657;
    RmaTransEventHdr  I863;
    RP  I776;
    RmaIbfPcode  I954;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I657;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I974;
    U  I975;
    RmaTransEventHdr  I863;
    RP  I776;
    RmaIbfPcode  I954;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I974;
    U  I975;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I976;
    RmaTransEventHdr  I863;
    RP  I776;
    RmaIbfPcode  I954;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I976;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I779;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1381;
        RP  I1394;
    } I754;
    RmaIbfPcode  I954;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I779;
    RmaEblk  I702;
    RmaIbfPcode  I954;
} RmaPortDelay;
typedef struct {
    U  I5;
    RP   I977[(4)];
} RmaRtlXEdgesHdr;
typedef struct {
    U  I5;
    US  I978;
    US  I600;
    RP  I979;
    RP  I980;
    RP  I981;
} RmaRtlEdgeBlockHdr;
typedef struct {
    RP  I982;
    RP  I983;
} RemoteDbsedLoad;
typedef struct {
    RmaEblk  I702;
    US  I984;
    US  I600;
    U  I461;
    RP  I985;
    RP   I783[(4)];
    RP   I785[(4)];
    RemoteDbsedLoad   I986[1];
} RmaRtlEdgeBlock;
typedef struct TableAssign_ {
    struct TableAssign_ * I849;
    struct TableAssign_ * I770;
    U  I5;
    U  I988 :1;
    U  I989 :1;
    U  I990 :2;
    U  I991 :1;
    U  I674 :8;
    U  I600 :19;
    RP  ptable;
    RP  I965;
} TableAssign;
typedef struct {
    U  I5;
    RP  I770;
    RP  I992;
} RmaTableAssignList;
typedef struct {
    RP  I982;
} RmaWakeupListCg;
typedef struct {
    U  I993;
    U  I674;
    RmaTimeStamp   I994[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I995;
} RmaConditionsMdb;
typedef struct {
    RP  I849;
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I849;
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1006;
} RmaTcCoreConditional;
typedef struct {
    RP  I849;
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1006;
    RP  I1007;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I849;
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1007;
    RP  I1008;
    U  I1009;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1011;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1006;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1006;
    RP  I1007;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1007;
    RP  I1008;
    U  I1009;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1007;
    RP  I1008;
    RP  I1011;
    U  I1009;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    RP  I1006;
    RP  I1011;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I996;
    RP  I697;
    U  I997;
    scalar  I958;
    scalar  I998;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :1;
    US  I1003 :1;
    US  I1004 :1;
    US  I1005 :5;
    U  I1012;
    RP  I1013;
    RP  I1014;
    RP  I1006;
    RP  I1015;
    RP  I1016;
    RmaTimeStamp  I1017;
} RmaTcCoreNochange;
typedef struct {
    RP  I1018;
    RP  I849;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I995;
    RmaTimeStamp  I1019;
    scalar  I1020;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I849;
    RP  I995;
    RmaTimeStamp  I1019;
    scalar  I1020;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I1019;
    scalar  I1020;
    US  I958;
    RP  I1007;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I849;
    RmaTimeStamp  I1019;
    scalar  I1020;
    US  I958;
    RP  I1007;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I1007;
    RP  I1021;
    U  I1009;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I1011;
    RP  I1007;
    RP  I1021;
    U  I1009;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I849;
    RP  I1007;
    RP  I1021;
    U  I1009;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I1022;
    U  I1023;
    FlatNodeNum  I1024;
    U  I857;
    U  I1025;
    U  I1026;
    RmaIbfPcode  I954;
    union {
        scalar  I1027;
        vec32  I1028;
        scalar  * I1029;
        vec32  * I1030;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I849;
    RP  I770;
    RP  I1031;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I1032;
    U  I1033 :1;
    U  I1034 :1;
    U  I1035 :1;
    U  I1036 :4;
    U  I600 :25;
    U  I1037;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1431;
        RmaSwitchGateInCbkListInfo  I2;
    } I671;
    RmaIbfPcode  I954;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I1038;
    scalar  val;
    scalar  I1039 :1;
    scalar  I1040 :1;
    scalar  I1041 :1;
    scalar  I1042 :1;
    scalar  I1043 :1;
    RP  I783;
    RP  I1044;
    RP  I1024;
    RP  I1045;
    RP  I1046;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I1039;
    UB  I1047;
    RmaNonEdgeLoadData1  * I977;
    RmaNonEdgeLoadData1  * I770;
} RmaNonEdgeLoadHdr1;
typedef struct RmaSubMasterSeqUdpLoad_ {
    RmaTableAssignList  * I1048;
    struct RmaSubMasterSeqUdpLoad_ * I1031;
    struct RmaSubMasterSeqUdpLoad_ * I849;
} RmaSubMasterSeqUdpLoad;
typedef struct RmaSubMasterSeqUdpList_ {
    RmaTableAssignList  * I1048;
    RmaSubMasterSeqUdpLoad  * I977;
    RmaSubMasterSeqUdpLoad  * I770;
} RmaSubMasterSeqUdpList;
typedef struct RmaChildClockProp_ {
    RP  I783;
    RP  I1050;
    RP  I1024;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I977;
    RmaChildClockProp  * I770;
} RmaChildClockPropList1;
typedef struct {
    U  I5;
    U  I1051;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I183 :5;
    U  I184 :12;
    U  I185 :1;
    U  I186 :2;
    U  I187 :1;
    U  I188 :1;
    U  I189 :1;
    U  I190 :9;
    U  I191;
    U  I192;
    void (* pfn)(void * I194, char val);
};
typedef struct clock_data {
    U  I199 :1;
    U  I200 :1;
    U  I201 :1;
    U  I202 :1;
    U  I183 :5;
    U  I184 :12;
    U  I203 :6;
    U  I204 :1;
    U  I186 :2;
    U  I187 :1;
    U  I190 :1;
    U  I205;
    U  I206;
    U  I207;
    U  I191;
    U  I208;
    U  I209;
    U  I210;
    U  I211;
    U  I212;
} HdbsClockData;
struct clock_hiconn {
    U  I216;
    U  I217;
    U  I191;
    U  I186;
};
typedef struct _RmaDaiCg {
    RP  I1052;
    RP  I1053;
    U  I1054;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I1052;
    RP  I1055;
    RP  I1056;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I1057;
} RmaDaiOptCg;
struct futq_slot2 {
    U  I732;
    U   I733[32];
};
struct futq_slot1 {
    U  I729;
    struct futq_slot2  I730[32];
};
struct futq_info {
    U  I725;
    U  I726;
    struct futq_slot1  I727[32];
};
struct futq {
    struct futq * I715;
    struct futq * I717;
    RmaEblk  * I718;
    RmaEblk  * I719;
    U  I707;
};
struct sched_table {
    struct futq * I720;
    struct futq I721;
    struct hash_bucket * I722;
    struct hash_bucket * I724;
};
struct dummyq_struct {
    clock_struct  I1061;
    EBLK  * I1062;
    EBLK  * I1063;
    struct futq * I1064;
    struct futq * I1065;
    struct futq * I1066;
    struct sched_table * I1067;
    struct futq_info * I1069;
    U  I1071;
    U  I1072;
    U  I1073;
    struct millenium * I1074;
    EBLK  * I1076;
    EBLK  * I1077;
    EBLK  * I1078;
    EBLK  * I1079;
    EBLK  * I1080;
    EBLK  * I1081;
    EBLK  * I1082;
    EBLK  * I1083;
    EBLK  * I1084;
    EBLK  * I1085;
    EBLK  * I1086;
    EBLK  * I1087;
    EBLK  * I1088;
    EBLK  * I1089;
    EBLK  * I1090;
    EBLK  * I1091;
    EBLK  * I1092;
    EBLK  * I1093;
    MPS  * I1094;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I703;
    EBLK  * I1095;
    int I1096;
    struct _lqueue * I744;
} Queue;
typedef struct {
    EBLK  I1098;
    U  I1099;
    union {
        void * pHeap;
        Queue  * pList;
    } I671;
    Queue   I1100[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern UB  * expandedClkValues;
extern US   xedges[];
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fHashTableSize;
extern U  fSkipStrChangeOnDelay;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void doMpdCommon(MPS* pmps);
extern TimeStamp GET_DIFF_DELAY_FUNC(TimeStamp ts);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void FsdbReportClkGlitch(UB*,U);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset, U gd_info, U encodeInPcode, void* propValue);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvalRtlEdgeLoads(RmaRtlEdgeBlockHdr *phdr, US clkEdge, scalar clkVal, scalar prevClkVal, scalar val4,   scalar prevval4);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, UB* pprevlist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void rmaRecordEvents(HsimNodeRecord *pnr);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern void rmaChangeListForMovedGates(UB clkVal, UB f10Edge, UB* subMasterVal, UB* plist, RP* p, U count);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hs_0_M_0_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_0_6__simv_daidir (UB  * pcode, scalar  val, U  I958);
void  hs_0_M_0_7__simv_daidir (UB  * pcode, vec32  * I1185, U  I958, U  I1194);
void  hs_0_M_0_10__simv_daidir (UB  * pcode, vec32  * I936);
void  hs_0_M_1_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_2_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_3_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_4_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_5_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_5_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_6_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_7_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_8_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_9_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_10_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_11_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_12_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_13_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_14_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_15_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_16_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_17_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_17_9__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_18_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_19_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_20_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_21_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_22_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_23_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_24_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_25_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_26_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_27_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_28_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_29_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_30_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_31_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_32_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_32_5__simv_daidir (UB  * pcode, UB  val);
void  hs_0_M_33_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_34_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_34_6__simv_daidir (UB  * pcode, scalar  val, U  I958);
void  hs_0_M_34_7__simv_daidir (UB  * pcode, vec32  * I1185, U  I958, U  I1194);
void  hs_0_M_34_10__simv_daidir (UB  * pcode, vec32  * I936);
void  hs_0_M_35_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_36_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_36_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_37_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_37_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_38_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_38_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_39_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_39_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_40_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_40_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_41_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_41_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_42_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_42_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_43_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_43_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_44_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_44_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_45_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_45_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_46_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_46_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_47_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_48_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_48_9__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_49_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_50_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_51_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_52_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_53_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_54_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_55_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_56_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_57_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_58_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_59_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_60_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_61_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_62_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_63_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_64_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_65_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_66_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_67_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_68_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_69_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_70_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_70_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_71_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_71_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_72_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_73_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_73_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_74_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_75_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_76_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_77_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_78_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_78_5__simv_daidir (UB  * pcode, U  I857);
void  hs_0_M_79_0__simv_daidir (UB  * pcode, vec32  * I936, U  I857);
void  hs_0_M_79_5__simv_daidir (UB  * pcode, U  I857);
void  hs_0_M_80_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_81_0__simv_daidir (UB  * pcode, scalar  val);
void  hsG_0__0 (struct dummyq_struct * I1108, EBLK  * I1109, U  I657);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

