
// ## AUTOGENERATED; DO NOT MODIFY
// ## num_rows_p = 8
// ## num_cols_p = 8
// ## num_dly_p = 8


  module bsg_rp_dly_line_unit_v3
      (input async_reset_neg_i
      , input trigger_i
      , input [63:0] ctl_one_hot_i
      , input  clk_i
      , output clk_o
      );
      wire lobit;
      TIELBWP7T30P140ULVT T0 (.ZN(lobit));
      wire hibit;
      TIEHBWP7T30P140ULVT T1 (.Z(hibit));
  

  wire fb_inv;
  CKND8BWP7T30P140ULVT I0 (.ZN(fb_inv), .I(clk_i));
  wire gate_en_sync_1_r, gate_en_sync_2_r;
  DFQD4BWP7T30P140ULVT S1 (.D(trigger_i), .CP(fb_inv), .Q(gate_en_sync_1_r));
  DFQD4BWP7T30P140ULVT S2 (.D(gate_en_sync_1_r), .CP(fb_inv), .Q(gate_en_sync_2_r));
  wire fb_gated;
  CKLNQD20BWP7T30P140ULVT CG0 (.Q(fb_gated), .CP(fb_inv), .E(gate_en_sync_2_r), .TE(lobit));
  wire [8:0] fb_col;
  assign fb_col[0] = 1'b0;


      bsg_rp_clk_gen_osc_v3_col col_0
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[0])
        ,.ctl_one_hot_i(ctl_one_hot_i[7:0])
        ,.clk_o(fb_col[1])
        );


      bsg_rp_clk_gen_osc_v3_col col_1
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[1])
        ,.ctl_one_hot_i(ctl_one_hot_i[15:8])
        ,.clk_o(fb_col[2])
        );


      bsg_rp_clk_gen_osc_v3_col col_2
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[2])
        ,.ctl_one_hot_i(ctl_one_hot_i[23:16])
        ,.clk_o(fb_col[3])
        );


      bsg_rp_clk_gen_osc_v3_col col_3
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[3])
        ,.ctl_one_hot_i(ctl_one_hot_i[31:24])
        ,.clk_o(fb_col[4])
        );


      bsg_rp_clk_gen_osc_v3_col col_4
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[4])
        ,.ctl_one_hot_i(ctl_one_hot_i[39:32])
        ,.clk_o(fb_col[5])
        );


      bsg_rp_clk_gen_osc_v3_col col_5
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[5])
        ,.ctl_one_hot_i(ctl_one_hot_i[47:40])
        ,.clk_o(fb_col[6])
        );


      bsg_rp_clk_gen_osc_v3_col col_6
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[6])
        ,.ctl_one_hot_i(ctl_one_hot_i[55:48])
        ,.clk_o(fb_col[7])
        );


      bsg_rp_clk_gen_osc_v3_col col_7
       (.async_reset_neg_i(async_reset_neg_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(clk_i)
        ,.clkfb_i(fb_col[7])
        ,.ctl_one_hot_i(ctl_one_hot_i[63:56])
        ,.clk_o(fb_col[8])
        );


  assign clk_o = fb_col[8];
endmodule


  module bsg_rp_dly_line_v3
   (input async_reset_i
    , input clk_i
    , output clk_o
    );
  wire async_reset_neg;
  INVD8BWP7T30P140ULVT I1 (.ZN(async_reset_neg), .I(async_reset_i));
  // State machine
  // Trigger off
  wire trigger_off, trigger_on;
  DFSNQD4BWP7T30P140ULVT D1 (.Q(trigger_off), .CP(clk_i), .D(trigger_on), .SDN(async_reset_neg));
  // Change counter
  wire counter_en;
  DFCNQD4BWP7T30P140ULVT D2 (.Q(counter_en), .CP(clk_i), .D(trigger_off), .CDN(async_reset_neg));
  // Pause
  wire pause;
  DFCNQD4BWP7T30P140ULVT D3 (.Q(pause), .CP(clk_i), .D(counter_en), .CDN(async_reset_neg));
  // Trigger on
  DFCNQD4BWP7T30P140ULVT D4 (.Q(trigger_on), .CP(clk_i), .D(pause), .CDN(async_reset_neg));
  wire [64:-1] ctl_n, ctl_r;
  wire clk_90;
  bsg_rp_dly_line_unit_v3 d90
   (.async_reset_neg_i(async_reset_neg_i)
    ,.trigger_i(trigger_on)
    ,.ctl_one_hot_i(ctl_r)
    ,.clk_i(clk_i)
    ,.clk_o(clk_90)
    );
  bsg_rp_dly_line_unit_v3 d180
   (.async_reset_neg_i(async_reset_neg_i)
    ,.trigger_i(trigger_on)
    ,.ctl_one_hot_i(ctl_r)
    ,.clk_i(clk_90)
    ,.clk_o(clk_180)
    );
  wire meta;
  DFNCND4BWP7T30P140ULVT meta_r (.Q(meta), .QN(), .CPN(clk_i), .CDN(async_reset_neg), .D(clk_180));
  wire meta_sync, meta_sync_sync, meta_sync_sync_inv;
  DFCND4BWP7T30P140ULVT bsg_SYNC_1_r (.Q(meta_sync), .QN(), .CP(clk_i), .D(meta), .CDN(async_reset_neg));
  DFCND4BWP7T30P140ULVT bsg_SYNC_2_r (.Q(meta_sync_sync), .QN(meta_sync_sync_inv), .CP(clk_i), .D(meta_sync), .CDN(async_reset_neg));
  wire shift_left, shift_right;
  AN2D4BWP7T30P140ULVT A2 (.A1(meta_sync_sync), .A2(counter_en), .Z(shift_left));
  AN2D4BWP7T30P140ULVT A1 (.A1(meta_sync_sync_inv), .A2(counter_en), .Z(shift_right));
  // Tie off the ends of the chain
  TIEHBWP7T30P140ULVT T0 (.Z(ctl_r[-1]));
  TIELBWP7T30P140ULVT T1 (.ZN(ctl_r[64]));
  wire [64-1:0] set, clr;


    ND2D4BWP7T30P140ULVT A01 (.A1(shift_right), .A2(ctl_r[-1]), .ZN(set[0]));
    ND2D4BWP7T30P140ULVT A02 (.A1(shift_left), .A2(ctl_r[1]), .ZN(clr[0]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_0 (.Q(ctl_r[0]), .QN(), .CP(clk_i), .CN(clr[0]), .SN(set[0]), .D(ctl_r[0]));
  

    ND2D4BWP7T30P140ULVT A11 (.A1(shift_right), .A2(ctl_r[0]), .ZN(set[1]));
    ND2D4BWP7T30P140ULVT A12 (.A1(shift_left), .A2(ctl_r[2]), .ZN(clr[1]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_1 (.Q(ctl_r[1]), .QN(), .CP(clk_i), .CN(clr[1]), .SN(set[1]), .D(ctl_r[1]));
  

    ND2D4BWP7T30P140ULVT A21 (.A1(shift_right), .A2(ctl_r[1]), .ZN(set[2]));
    ND2D4BWP7T30P140ULVT A22 (.A1(shift_left), .A2(ctl_r[3]), .ZN(clr[2]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_2 (.Q(ctl_r[2]), .QN(), .CP(clk_i), .CN(clr[2]), .SN(set[2]), .D(ctl_r[2]));
  

    ND2D4BWP7T30P140ULVT A31 (.A1(shift_right), .A2(ctl_r[2]), .ZN(set[3]));
    ND2D4BWP7T30P140ULVT A32 (.A1(shift_left), .A2(ctl_r[4]), .ZN(clr[3]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_3 (.Q(ctl_r[3]), .QN(), .CP(clk_i), .CN(clr[3]), .SN(set[3]), .D(ctl_r[3]));
  

    ND2D4BWP7T30P140ULVT A41 (.A1(shift_right), .A2(ctl_r[3]), .ZN(set[4]));
    ND2D4BWP7T30P140ULVT A42 (.A1(shift_left), .A2(ctl_r[5]), .ZN(clr[4]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_4 (.Q(ctl_r[4]), .QN(), .CP(clk_i), .CN(clr[4]), .SN(set[4]), .D(ctl_r[4]));
  

    ND2D4BWP7T30P140ULVT A51 (.A1(shift_right), .A2(ctl_r[4]), .ZN(set[5]));
    ND2D4BWP7T30P140ULVT A52 (.A1(shift_left), .A2(ctl_r[6]), .ZN(clr[5]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_5 (.Q(ctl_r[5]), .QN(), .CP(clk_i), .CN(clr[5]), .SN(set[5]), .D(ctl_r[5]));
  

    ND2D4BWP7T30P140ULVT A61 (.A1(shift_right), .A2(ctl_r[5]), .ZN(set[6]));
    ND2D4BWP7T30P140ULVT A62 (.A1(shift_left), .A2(ctl_r[7]), .ZN(clr[6]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_6 (.Q(ctl_r[6]), .QN(), .CP(clk_i), .CN(clr[6]), .SN(set[6]), .D(ctl_r[6]));
  

    ND2D4BWP7T30P140ULVT A71 (.A1(shift_right), .A2(ctl_r[6]), .ZN(set[7]));
    ND2D4BWP7T30P140ULVT A72 (.A1(shift_left), .A2(ctl_r[8]), .ZN(clr[7]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_7 (.Q(ctl_r[7]), .QN(), .CP(clk_i), .CN(clr[7]), .SN(set[7]), .D(ctl_r[7]));
  

    ND2D4BWP7T30P140ULVT A81 (.A1(shift_right), .A2(ctl_r[7]), .ZN(set[8]));
    ND2D4BWP7T30P140ULVT A82 (.A1(shift_left), .A2(ctl_r[9]), .ZN(clr[8]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_8 (.Q(ctl_r[8]), .QN(), .CP(clk_i), .CN(clr[8]), .SN(set[8]), .D(ctl_r[8]));
  

    ND2D4BWP7T30P140ULVT A91 (.A1(shift_right), .A2(ctl_r[8]), .ZN(set[9]));
    ND2D4BWP7T30P140ULVT A92 (.A1(shift_left), .A2(ctl_r[10]), .ZN(clr[9]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_9 (.Q(ctl_r[9]), .QN(), .CP(clk_i), .CN(clr[9]), .SN(set[9]), .D(ctl_r[9]));
  

    ND2D4BWP7T30P140ULVT A101 (.A1(shift_right), .A2(ctl_r[9]), .ZN(set[10]));
    ND2D4BWP7T30P140ULVT A102 (.A1(shift_left), .A2(ctl_r[11]), .ZN(clr[10]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_10 (.Q(ctl_r[10]), .QN(), .CP(clk_i), .CN(clr[10]), .SN(set[10]), .D(ctl_r[10]));
  

    ND2D4BWP7T30P140ULVT A111 (.A1(shift_right), .A2(ctl_r[10]), .ZN(set[11]));
    ND2D4BWP7T30P140ULVT A112 (.A1(shift_left), .A2(ctl_r[12]), .ZN(clr[11]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_11 (.Q(ctl_r[11]), .QN(), .CP(clk_i), .CN(clr[11]), .SN(set[11]), .D(ctl_r[11]));
  

    ND2D4BWP7T30P140ULVT A121 (.A1(shift_right), .A2(ctl_r[11]), .ZN(set[12]));
    ND2D4BWP7T30P140ULVT A122 (.A1(shift_left), .A2(ctl_r[13]), .ZN(clr[12]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_12 (.Q(ctl_r[12]), .QN(), .CP(clk_i), .CN(clr[12]), .SN(set[12]), .D(ctl_r[12]));
  

    ND2D4BWP7T30P140ULVT A131 (.A1(shift_right), .A2(ctl_r[12]), .ZN(set[13]));
    ND2D4BWP7T30P140ULVT A132 (.A1(shift_left), .A2(ctl_r[14]), .ZN(clr[13]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_13 (.Q(ctl_r[13]), .QN(), .CP(clk_i), .CN(clr[13]), .SN(set[13]), .D(ctl_r[13]));
  

    ND2D4BWP7T30P140ULVT A141 (.A1(shift_right), .A2(ctl_r[13]), .ZN(set[14]));
    ND2D4BWP7T30P140ULVT A142 (.A1(shift_left), .A2(ctl_r[15]), .ZN(clr[14]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_14 (.Q(ctl_r[14]), .QN(), .CP(clk_i), .CN(clr[14]), .SN(set[14]), .D(ctl_r[14]));
  

    ND2D4BWP7T30P140ULVT A151 (.A1(shift_right), .A2(ctl_r[14]), .ZN(set[15]));
    ND2D4BWP7T30P140ULVT A152 (.A1(shift_left), .A2(ctl_r[16]), .ZN(clr[15]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_15 (.Q(ctl_r[15]), .QN(), .CP(clk_i), .CN(clr[15]), .SN(set[15]), .D(ctl_r[15]));
  

    ND2D4BWP7T30P140ULVT A161 (.A1(shift_right), .A2(ctl_r[15]), .ZN(set[16]));
    ND2D4BWP7T30P140ULVT A162 (.A1(shift_left), .A2(ctl_r[17]), .ZN(clr[16]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_16 (.Q(ctl_r[16]), .QN(), .CP(clk_i), .CN(clr[16]), .SN(set[16]), .D(ctl_r[16]));
  

    ND2D4BWP7T30P140ULVT A171 (.A1(shift_right), .A2(ctl_r[16]), .ZN(set[17]));
    ND2D4BWP7T30P140ULVT A172 (.A1(shift_left), .A2(ctl_r[18]), .ZN(clr[17]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_17 (.Q(ctl_r[17]), .QN(), .CP(clk_i), .CN(clr[17]), .SN(set[17]), .D(ctl_r[17]));
  

    ND2D4BWP7T30P140ULVT A181 (.A1(shift_right), .A2(ctl_r[17]), .ZN(set[18]));
    ND2D4BWP7T30P140ULVT A182 (.A1(shift_left), .A2(ctl_r[19]), .ZN(clr[18]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_18 (.Q(ctl_r[18]), .QN(), .CP(clk_i), .CN(clr[18]), .SN(set[18]), .D(ctl_r[18]));
  

    ND2D4BWP7T30P140ULVT A191 (.A1(shift_right), .A2(ctl_r[18]), .ZN(set[19]));
    ND2D4BWP7T30P140ULVT A192 (.A1(shift_left), .A2(ctl_r[20]), .ZN(clr[19]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_19 (.Q(ctl_r[19]), .QN(), .CP(clk_i), .CN(clr[19]), .SN(set[19]), .D(ctl_r[19]));
  

    ND2D4BWP7T30P140ULVT A201 (.A1(shift_right), .A2(ctl_r[19]), .ZN(set[20]));
    ND2D4BWP7T30P140ULVT A202 (.A1(shift_left), .A2(ctl_r[21]), .ZN(clr[20]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_20 (.Q(ctl_r[20]), .QN(), .CP(clk_i), .CN(clr[20]), .SN(set[20]), .D(ctl_r[20]));
  

    ND2D4BWP7T30P140ULVT A211 (.A1(shift_right), .A2(ctl_r[20]), .ZN(set[21]));
    ND2D4BWP7T30P140ULVT A212 (.A1(shift_left), .A2(ctl_r[22]), .ZN(clr[21]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_21 (.Q(ctl_r[21]), .QN(), .CP(clk_i), .CN(clr[21]), .SN(set[21]), .D(ctl_r[21]));
  

    ND2D4BWP7T30P140ULVT A221 (.A1(shift_right), .A2(ctl_r[21]), .ZN(set[22]));
    ND2D4BWP7T30P140ULVT A222 (.A1(shift_left), .A2(ctl_r[23]), .ZN(clr[22]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_22 (.Q(ctl_r[22]), .QN(), .CP(clk_i), .CN(clr[22]), .SN(set[22]), .D(ctl_r[22]));
  

    ND2D4BWP7T30P140ULVT A231 (.A1(shift_right), .A2(ctl_r[22]), .ZN(set[23]));
    ND2D4BWP7T30P140ULVT A232 (.A1(shift_left), .A2(ctl_r[24]), .ZN(clr[23]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_23 (.Q(ctl_r[23]), .QN(), .CP(clk_i), .CN(clr[23]), .SN(set[23]), .D(ctl_r[23]));
  

    ND2D4BWP7T30P140ULVT A241 (.A1(shift_right), .A2(ctl_r[23]), .ZN(set[24]));
    ND2D4BWP7T30P140ULVT A242 (.A1(shift_left), .A2(ctl_r[25]), .ZN(clr[24]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_24 (.Q(ctl_r[24]), .QN(), .CP(clk_i), .CN(clr[24]), .SN(set[24]), .D(ctl_r[24]));
  

    ND2D4BWP7T30P140ULVT A251 (.A1(shift_right), .A2(ctl_r[24]), .ZN(set[25]));
    ND2D4BWP7T30P140ULVT A252 (.A1(shift_left), .A2(ctl_r[26]), .ZN(clr[25]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_25 (.Q(ctl_r[25]), .QN(), .CP(clk_i), .CN(clr[25]), .SN(set[25]), .D(ctl_r[25]));
  

    ND2D4BWP7T30P140ULVT A261 (.A1(shift_right), .A2(ctl_r[25]), .ZN(set[26]));
    ND2D4BWP7T30P140ULVT A262 (.A1(shift_left), .A2(ctl_r[27]), .ZN(clr[26]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_26 (.Q(ctl_r[26]), .QN(), .CP(clk_i), .CN(clr[26]), .SN(set[26]), .D(ctl_r[26]));
  

    ND2D4BWP7T30P140ULVT A271 (.A1(shift_right), .A2(ctl_r[26]), .ZN(set[27]));
    ND2D4BWP7T30P140ULVT A272 (.A1(shift_left), .A2(ctl_r[28]), .ZN(clr[27]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_27 (.Q(ctl_r[27]), .QN(), .CP(clk_i), .CN(clr[27]), .SN(set[27]), .D(ctl_r[27]));
  

    ND2D4BWP7T30P140ULVT A281 (.A1(shift_right), .A2(ctl_r[27]), .ZN(set[28]));
    ND2D4BWP7T30P140ULVT A282 (.A1(shift_left), .A2(ctl_r[29]), .ZN(clr[28]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_28 (.Q(ctl_r[28]), .QN(), .CP(clk_i), .CN(clr[28]), .SN(set[28]), .D(ctl_r[28]));
  

    ND2D4BWP7T30P140ULVT A291 (.A1(shift_right), .A2(ctl_r[28]), .ZN(set[29]));
    ND2D4BWP7T30P140ULVT A292 (.A1(shift_left), .A2(ctl_r[30]), .ZN(clr[29]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_29 (.Q(ctl_r[29]), .QN(), .CP(clk_i), .CN(clr[29]), .SN(set[29]), .D(ctl_r[29]));
  

    ND2D4BWP7T30P140ULVT A301 (.A1(shift_right), .A2(ctl_r[29]), .ZN(set[30]));
    ND2D4BWP7T30P140ULVT A302 (.A1(shift_left), .A2(ctl_r[31]), .ZN(clr[30]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_30 (.Q(ctl_r[30]), .QN(), .CP(clk_i), .CN(clr[30]), .SN(set[30]), .D(ctl_r[30]));
  

    ND2D4BWP7T30P140ULVT A311 (.A1(shift_right), .A2(ctl_r[30]), .ZN(set[31]));
    ND2D4BWP7T30P140ULVT A312 (.A1(shift_left), .A2(ctl_r[32]), .ZN(clr[31]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_31 (.Q(ctl_r[31]), .QN(), .CP(clk_i), .CN(clr[31]), .SN(set[31]), .D(ctl_r[31]));
  

    ND2D4BWP7T30P140ULVT A321 (.A1(shift_right), .A2(ctl_r[31]), .ZN(set[32]));
    ND2D4BWP7T30P140ULVT A322 (.A1(shift_left), .A2(ctl_r[33]), .ZN(clr[32]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_32 (.Q(ctl_r[32]), .QN(), .CP(clk_i), .CN(clr[32]), .SN(set[32]), .D(ctl_r[32]));
  

    ND2D4BWP7T30P140ULVT A331 (.A1(shift_right), .A2(ctl_r[32]), .ZN(set[33]));
    ND2D4BWP7T30P140ULVT A332 (.A1(shift_left), .A2(ctl_r[34]), .ZN(clr[33]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_33 (.Q(ctl_r[33]), .QN(), .CP(clk_i), .CN(clr[33]), .SN(set[33]), .D(ctl_r[33]));
  

    ND2D4BWP7T30P140ULVT A341 (.A1(shift_right), .A2(ctl_r[33]), .ZN(set[34]));
    ND2D4BWP7T30P140ULVT A342 (.A1(shift_left), .A2(ctl_r[35]), .ZN(clr[34]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_34 (.Q(ctl_r[34]), .QN(), .CP(clk_i), .CN(clr[34]), .SN(set[34]), .D(ctl_r[34]));
  

    ND2D4BWP7T30P140ULVT A351 (.A1(shift_right), .A2(ctl_r[34]), .ZN(set[35]));
    ND2D4BWP7T30P140ULVT A352 (.A1(shift_left), .A2(ctl_r[36]), .ZN(clr[35]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_35 (.Q(ctl_r[35]), .QN(), .CP(clk_i), .CN(clr[35]), .SN(set[35]), .D(ctl_r[35]));
  

    ND2D4BWP7T30P140ULVT A361 (.A1(shift_right), .A2(ctl_r[35]), .ZN(set[36]));
    ND2D4BWP7T30P140ULVT A362 (.A1(shift_left), .A2(ctl_r[37]), .ZN(clr[36]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_36 (.Q(ctl_r[36]), .QN(), .CP(clk_i), .CN(clr[36]), .SN(set[36]), .D(ctl_r[36]));
  

    ND2D4BWP7T30P140ULVT A371 (.A1(shift_right), .A2(ctl_r[36]), .ZN(set[37]));
    ND2D4BWP7T30P140ULVT A372 (.A1(shift_left), .A2(ctl_r[38]), .ZN(clr[37]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_37 (.Q(ctl_r[37]), .QN(), .CP(clk_i), .CN(clr[37]), .SN(set[37]), .D(ctl_r[37]));
  

    ND2D4BWP7T30P140ULVT A381 (.A1(shift_right), .A2(ctl_r[37]), .ZN(set[38]));
    ND2D4BWP7T30P140ULVT A382 (.A1(shift_left), .A2(ctl_r[39]), .ZN(clr[38]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_38 (.Q(ctl_r[38]), .QN(), .CP(clk_i), .CN(clr[38]), .SN(set[38]), .D(ctl_r[38]));
  

    ND2D4BWP7T30P140ULVT A391 (.A1(shift_right), .A2(ctl_r[38]), .ZN(set[39]));
    ND2D4BWP7T30P140ULVT A392 (.A1(shift_left), .A2(ctl_r[40]), .ZN(clr[39]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_39 (.Q(ctl_r[39]), .QN(), .CP(clk_i), .CN(clr[39]), .SN(set[39]), .D(ctl_r[39]));
  

    ND2D4BWP7T30P140ULVT A401 (.A1(shift_right), .A2(ctl_r[39]), .ZN(set[40]));
    ND2D4BWP7T30P140ULVT A402 (.A1(shift_left), .A2(ctl_r[41]), .ZN(clr[40]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_40 (.Q(ctl_r[40]), .QN(), .CP(clk_i), .CN(clr[40]), .SN(set[40]), .D(ctl_r[40]));
  

    ND2D4BWP7T30P140ULVT A411 (.A1(shift_right), .A2(ctl_r[40]), .ZN(set[41]));
    ND2D4BWP7T30P140ULVT A412 (.A1(shift_left), .A2(ctl_r[42]), .ZN(clr[41]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_41 (.Q(ctl_r[41]), .QN(), .CP(clk_i), .CN(clr[41]), .SN(set[41]), .D(ctl_r[41]));
  

    ND2D4BWP7T30P140ULVT A421 (.A1(shift_right), .A2(ctl_r[41]), .ZN(set[42]));
    ND2D4BWP7T30P140ULVT A422 (.A1(shift_left), .A2(ctl_r[43]), .ZN(clr[42]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_42 (.Q(ctl_r[42]), .QN(), .CP(clk_i), .CN(clr[42]), .SN(set[42]), .D(ctl_r[42]));
  

    ND2D4BWP7T30P140ULVT A431 (.A1(shift_right), .A2(ctl_r[42]), .ZN(set[43]));
    ND2D4BWP7T30P140ULVT A432 (.A1(shift_left), .A2(ctl_r[44]), .ZN(clr[43]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_43 (.Q(ctl_r[43]), .QN(), .CP(clk_i), .CN(clr[43]), .SN(set[43]), .D(ctl_r[43]));
  

    ND2D4BWP7T30P140ULVT A441 (.A1(shift_right), .A2(ctl_r[43]), .ZN(set[44]));
    ND2D4BWP7T30P140ULVT A442 (.A1(shift_left), .A2(ctl_r[45]), .ZN(clr[44]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_44 (.Q(ctl_r[44]), .QN(), .CP(clk_i), .CN(clr[44]), .SN(set[44]), .D(ctl_r[44]));
  

    ND2D4BWP7T30P140ULVT A451 (.A1(shift_right), .A2(ctl_r[44]), .ZN(set[45]));
    ND2D4BWP7T30P140ULVT A452 (.A1(shift_left), .A2(ctl_r[46]), .ZN(clr[45]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_45 (.Q(ctl_r[45]), .QN(), .CP(clk_i), .CN(clr[45]), .SN(set[45]), .D(ctl_r[45]));
  

    ND2D4BWP7T30P140ULVT A461 (.A1(shift_right), .A2(ctl_r[45]), .ZN(set[46]));
    ND2D4BWP7T30P140ULVT A462 (.A1(shift_left), .A2(ctl_r[47]), .ZN(clr[46]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_46 (.Q(ctl_r[46]), .QN(), .CP(clk_i), .CN(clr[46]), .SN(set[46]), .D(ctl_r[46]));
  

    ND2D4BWP7T30P140ULVT A471 (.A1(shift_right), .A2(ctl_r[46]), .ZN(set[47]));
    ND2D4BWP7T30P140ULVT A472 (.A1(shift_left), .A2(ctl_r[48]), .ZN(clr[47]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_47 (.Q(ctl_r[47]), .QN(), .CP(clk_i), .CN(clr[47]), .SN(set[47]), .D(ctl_r[47]));
  

    ND2D4BWP7T30P140ULVT A481 (.A1(shift_right), .A2(ctl_r[47]), .ZN(set[48]));
    ND2D4BWP7T30P140ULVT A482 (.A1(shift_left), .A2(ctl_r[49]), .ZN(clr[48]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_48 (.Q(ctl_r[48]), .QN(), .CP(clk_i), .CN(clr[48]), .SN(set[48]), .D(ctl_r[48]));
  

    ND2D4BWP7T30P140ULVT A491 (.A1(shift_right), .A2(ctl_r[48]), .ZN(set[49]));
    ND2D4BWP7T30P140ULVT A492 (.A1(shift_left), .A2(ctl_r[50]), .ZN(clr[49]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_49 (.Q(ctl_r[49]), .QN(), .CP(clk_i), .CN(clr[49]), .SN(set[49]), .D(ctl_r[49]));
  

    ND2D4BWP7T30P140ULVT A501 (.A1(shift_right), .A2(ctl_r[49]), .ZN(set[50]));
    ND2D4BWP7T30P140ULVT A502 (.A1(shift_left), .A2(ctl_r[51]), .ZN(clr[50]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_50 (.Q(ctl_r[50]), .QN(), .CP(clk_i), .CN(clr[50]), .SN(set[50]), .D(ctl_r[50]));
  

    ND2D4BWP7T30P140ULVT A511 (.A1(shift_right), .A2(ctl_r[50]), .ZN(set[51]));
    ND2D4BWP7T30P140ULVT A512 (.A1(shift_left), .A2(ctl_r[52]), .ZN(clr[51]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_51 (.Q(ctl_r[51]), .QN(), .CP(clk_i), .CN(clr[51]), .SN(set[51]), .D(ctl_r[51]));
  

    ND2D4BWP7T30P140ULVT A521 (.A1(shift_right), .A2(ctl_r[51]), .ZN(set[52]));
    ND2D4BWP7T30P140ULVT A522 (.A1(shift_left), .A2(ctl_r[53]), .ZN(clr[52]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_52 (.Q(ctl_r[52]), .QN(), .CP(clk_i), .CN(clr[52]), .SN(set[52]), .D(ctl_r[52]));
  

    ND2D4BWP7T30P140ULVT A531 (.A1(shift_right), .A2(ctl_r[52]), .ZN(set[53]));
    ND2D4BWP7T30P140ULVT A532 (.A1(shift_left), .A2(ctl_r[54]), .ZN(clr[53]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_53 (.Q(ctl_r[53]), .QN(), .CP(clk_i), .CN(clr[53]), .SN(set[53]), .D(ctl_r[53]));
  

    ND2D4BWP7T30P140ULVT A541 (.A1(shift_right), .A2(ctl_r[53]), .ZN(set[54]));
    ND2D4BWP7T30P140ULVT A542 (.A1(shift_left), .A2(ctl_r[55]), .ZN(clr[54]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_54 (.Q(ctl_r[54]), .QN(), .CP(clk_i), .CN(clr[54]), .SN(set[54]), .D(ctl_r[54]));
  

    ND2D4BWP7T30P140ULVT A551 (.A1(shift_right), .A2(ctl_r[54]), .ZN(set[55]));
    ND2D4BWP7T30P140ULVT A552 (.A1(shift_left), .A2(ctl_r[56]), .ZN(clr[55]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_55 (.Q(ctl_r[55]), .QN(), .CP(clk_i), .CN(clr[55]), .SN(set[55]), .D(ctl_r[55]));
  

    ND2D4BWP7T30P140ULVT A561 (.A1(shift_right), .A2(ctl_r[55]), .ZN(set[56]));
    ND2D4BWP7T30P140ULVT A562 (.A1(shift_left), .A2(ctl_r[57]), .ZN(clr[56]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_56 (.Q(ctl_r[56]), .QN(), .CP(clk_i), .CN(clr[56]), .SN(set[56]), .D(ctl_r[56]));
  

    ND2D4BWP7T30P140ULVT A571 (.A1(shift_right), .A2(ctl_r[56]), .ZN(set[57]));
    ND2D4BWP7T30P140ULVT A572 (.A1(shift_left), .A2(ctl_r[58]), .ZN(clr[57]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_57 (.Q(ctl_r[57]), .QN(), .CP(clk_i), .CN(clr[57]), .SN(set[57]), .D(ctl_r[57]));
  

    ND2D4BWP7T30P140ULVT A581 (.A1(shift_right), .A2(ctl_r[57]), .ZN(set[58]));
    ND2D4BWP7T30P140ULVT A582 (.A1(shift_left), .A2(ctl_r[59]), .ZN(clr[58]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_58 (.Q(ctl_r[58]), .QN(), .CP(clk_i), .CN(clr[58]), .SN(set[58]), .D(ctl_r[58]));
  

    ND2D4BWP7T30P140ULVT A591 (.A1(shift_right), .A2(ctl_r[58]), .ZN(set[59]));
    ND2D4BWP7T30P140ULVT A592 (.A1(shift_left), .A2(ctl_r[60]), .ZN(clr[59]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_59 (.Q(ctl_r[59]), .QN(), .CP(clk_i), .CN(clr[59]), .SN(set[59]), .D(ctl_r[59]));
  

    ND2D4BWP7T30P140ULVT A601 (.A1(shift_right), .A2(ctl_r[59]), .ZN(set[60]));
    ND2D4BWP7T30P140ULVT A602 (.A1(shift_left), .A2(ctl_r[61]), .ZN(clr[60]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_60 (.Q(ctl_r[60]), .QN(), .CP(clk_i), .CN(clr[60]), .SN(set[60]), .D(ctl_r[60]));
  

    ND2D4BWP7T30P140ULVT A611 (.A1(shift_right), .A2(ctl_r[60]), .ZN(set[61]));
    ND2D4BWP7T30P140ULVT A612 (.A1(shift_left), .A2(ctl_r[62]), .ZN(clr[61]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_61 (.Q(ctl_r[61]), .QN(), .CP(clk_i), .CN(clr[61]), .SN(set[61]), .D(ctl_r[61]));
  

    ND2D4BWP7T30P140ULVT A621 (.A1(shift_right), .A2(ctl_r[61]), .ZN(set[62]));
    ND2D4BWP7T30P140ULVT A622 (.A1(shift_left), .A2(ctl_r[63]), .ZN(clr[62]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_62 (.Q(ctl_r[62]), .QN(), .CP(clk_i), .CN(clr[62]), .SN(set[62]), .D(ctl_r[62]));
  

    ND2D4BWP7T30P140ULVT A631 (.A1(shift_right), .A2(ctl_r[62]), .ZN(set[63]));
    ND2D4BWP7T30P140ULVT A632 (.A1(shift_left), .A2(ctl_r[64]), .ZN(clr[63]));
    DFKCSND4BWP7T30P140ULVT ctl_reg_63 (.Q(ctl_r[63]), .QN(), .CP(clk_i), .CN(clr[63]), .SN(set[63]), .D(ctl_r[63]));
  

  endmodule

