//==================================================
// This file contains the Excluded objects
// Generated By User: dcjung
// Format Version: 2
// Date: Thu Nov  7 19:47:03 2019
// ExclMode: default
//==================================================
CHECKSUM: "3454857118 4212564062"
INSTANCE: testbench.DUT.decode0
Block 2 "3818645615" "decode_o.size_op = 2'b11;"
CHECKSUM: "3751605485 1361462809"
INSTANCE: testbench.DUT.dma0.out_fifo
Block 10 "4141722622" "full_r <= ((((~empty_r) & enq_i) & (~deq_i)) | (full_r & (~(deq_i ^ enq_i))));"
CHECKSUM: "1876878299 3164324781"
INSTANCE: testbench.DUT.miss_fifo0
Block 33 "3917637695" "deque = 1'b0;"
