//==================================================
// This file contains the Excluded objects
// Generated By User: dcjung
// Format Version: 2
// Date: Sat Nov  9 00:48:20 2019
// ExclMode: default
//==================================================
CHECKSUM: "4251363632"
INSTANCE:testbench.DUT.bc
CHECKSUM: "1309746545"
INSTANCE:testbench.DUT.blc
CHECKSUM: "2905631562"
INSTANCE:testbench.DUT.ac
CHECKSUM: "3272423538"
INSTANCE:testbench.DUT.bc.half_mux
CHECKSUM: "3272423538"
INSTANCE:testbench.DUT.bc.byte_mux
CHECKSUM: "3186318530"
INSTANCE:testbench.dma_model
CHECKSUM: "3724579720"
INSTANCE:testbench.clock_gen
CHECKSUM: "4045973507"
INSTANCE:testbench.yumi_gen
CHECKSUM: "783602680"
INSTANCE:testbench.trace_replay
CHECKSUM: "3168410882"
INSTANCE:testbench.test_rom
CHECKSUM: "714139277"
INSTANCE:testbench.reset_gen
CHECKSUM: "4152672392"
INSTANCE:testbench.DUT.tc
CHECKSUM: "1876878299 3164324781"
INSTANCE: testbench.DUT.miss_fifo0
Block 33 "3917637695" "deque = 1'b0;"
CHECKSUM: "1876878299 1428304593"
INSTANCE: testbench.DUT.miss_fifo0
Branch 5 "3896930086" "rollback_i" (13) "rollback_i 0,-,1,1,-,-,-,-,-,default,-,-,-,-,-,-,-,-,-,-,-"
CHECKSUM: "3751605485 1361462809"
INSTANCE: testbench.DUT.dma0.out_fifo
Block 10 "4141722622" "full_r <= ((((~empty_r) & enq_i) & (~deq_i)) | (full_r & (~(deq_i ^ enq_i))));"
CHECKSUM: "3751605485 896226750"
INSTANCE: testbench.DUT.dma0.out_fifo
Branch 0 "2341444785" "reset_i" (5) "reset_i 0,-,-,1"
CHECKSUM: "3454857118 4212564062"
INSTANCE: testbench.DUT.decode0
Block 2 "3818645615" "decode_o.size_op = 2'b11;"
CHECKSUM: "3454857118 3395022599"
INSTANCE: testbench.DUT.decode0
Branch 0 "2519985158" "opcode_i" (0) "opcode_i LD SD "
CHECKSUM: "505412087 1352501511"
INSTANCE: testbench.DUT.dma0
Fsm dma_state_r "1352501511"
Transition SEND_REFILL_ADDR->IDLE "1->0"
Transition SEND_EVICT_ADDR->IDLE "2->0"
Transition SEND_EVICT_DATA->IDLE "3->0"
Transition RECV_REFILL_DATA->IDLE "4->0"
CHECKSUM: "4069356448 1095362285"
INSTANCE: testbench.DUT.mhu0
Fsm mhu_state_r "1756338327"
Transition READ_TAG1->IDLE "4->0"
Transition SEND_DMA_REQ1->IDLE "5->0"
Transition WAIT_DMA_DONE->IDLE "6->0"
Transition DEQUEUE_MODE->IDLE "7->0"
Transition READ_TAG2->IDLE "8->0"
Transition SEND_DMA_REQ2->IDLE "9->0"
Transition SCAN_MODE->IDLE "10->0"
CHECKSUM: "2209695014 3834999291"
MODULE: bsg_encode_one_hot
Branch 0 "2321516876" "(((i - 1) & i) == '0)"
