TOP = ../../..
BSG_TESTME_FILES = bsg_counter_clear_up.sv
BSG_TESTME_DIR = $(TOP)/bsg_misc
BSG_MISC_FILES = bsg_defines.sv
BSG_TEST_FILES = bsg_nonsynth_clock_gen.sv
TEST_MAIN = test_bsg.sv
TEST_MODULE = test_bsg

CYCLE_TIME_P = 10
scan_params = CYCLE_TIME_P

include ../../Makefile.sim
