//This file is automatically generated by python script ./bsg_adder_wallace_tree_generator.py with N = 18. Do not modify.
module bsg_adder_wallace_tree_18 #(
  parameter integer width_p = "inv"
)(
  input [17:0][width_p-1:0] ops_i
  ,output [4+width_p:0] resA_o
  ,output [4+width_p:0] resB_o
);
wire [width_p-1:0] csa_0_0_res_o;
wire [width_p-1:0] csa_0_0_car_o;
wire [width_p-1:0] csa_0_1_res_o;
wire [width_p-1:0] csa_0_1_car_o;
wire [width_p-1:0] csa_0_2_res_o;
wire [width_p-1:0] csa_0_2_car_o;
wire [width_p-1:0] csa_0_3_res_o;
wire [width_p-1:0] csa_0_3_car_o;
wire [width_p-1:0] csa_0_4_res_o;
wire [width_p-1:0] csa_0_4_car_o;
wire [width_p-1:0] csa_0_5_res_o;
wire [width_p-1:0] csa_0_5_car_o;
wire [width_p+0:0] csa_1_0_res_o;
wire [width_p+0:0] csa_1_0_car_o;
wire [width_p+0:0] csa_1_1_res_o;
wire [width_p+0:0] csa_1_1_car_o;
wire [width_p+0:0] csa_1_2_res_o;
wire [width_p+0:0] csa_1_2_car_o;
wire [width_p+0:0] csa_1_3_res_o;
wire [width_p+0:0] csa_1_3_car_o;
wire [width_p+1:0] csa_2_0_res_o;
wire [width_p+1:0] csa_2_0_car_o;
wire [width_p+1:0] csa_2_1_res_o;
wire [width_p+1:0] csa_2_1_car_o;
wire [width_p+2:0] csa_3_0_res_o;
wire [width_p+2:0] csa_3_0_car_o;
wire [width_p+2:0] csa_3_1_res_o;
wire [width_p+2:0] csa_3_1_car_o;
wire [width_p+3:0] csa_4_0_res_o;
wire [width_p+3:0] csa_4_0_car_o;
wire [width_p+4:0] csa_5_0_res_o;
wire [width_p+4:0] csa_5_0_car_o;

bsg_adder_carry_save#(
  .width_p(width_p+0)
) csa_0_0 (
  .opA_i(ops_i[0])
  ,.opB_i(ops_i[1])
  ,.opC_i(ops_i[2])
  ,.res_o(csa_0_0_res_o)
  ,.car_o(csa_0_0_car_o)
);

wire [width_p+0:0] csa_internal_wire_0 = {1'b0, csa_0_0_res_o};
wire [width_p+0:0] csa_internal_wire_1 = {csa_0_0_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+0)
) csa_0_1 (
  .opA_i(ops_i[3])
  ,.opB_i(ops_i[4])
  ,.opC_i(ops_i[5])
  ,.res_o(csa_0_1_res_o)
  ,.car_o(csa_0_1_car_o)
);

wire [width_p+0:0] csa_internal_wire_2 = {1'b0, csa_0_1_res_o};
wire [width_p+0:0] csa_internal_wire_3 = {csa_0_1_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+0)
) csa_0_2 (
  .opA_i(ops_i[6])
  ,.opB_i(ops_i[7])
  ,.opC_i(ops_i[8])
  ,.res_o(csa_0_2_res_o)
  ,.car_o(csa_0_2_car_o)
);

wire [width_p+0:0] csa_internal_wire_4 = {1'b0, csa_0_2_res_o};
wire [width_p+0:0] csa_internal_wire_5 = {csa_0_2_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+0)
) csa_0_3 (
  .opA_i(ops_i[9])
  ,.opB_i(ops_i[10])
  ,.opC_i(ops_i[11])
  ,.res_o(csa_0_3_res_o)
  ,.car_o(csa_0_3_car_o)
);

wire [width_p+0:0] csa_internal_wire_6 = {1'b0, csa_0_3_res_o};
wire [width_p+0:0] csa_internal_wire_7 = {csa_0_3_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+0)
) csa_0_4 (
  .opA_i(ops_i[12])
  ,.opB_i(ops_i[13])
  ,.opC_i(ops_i[14])
  ,.res_o(csa_0_4_res_o)
  ,.car_o(csa_0_4_car_o)
);

wire [width_p+0:0] csa_internal_wire_8 = {1'b0, csa_0_4_res_o};
wire [width_p+0:0] csa_internal_wire_9 = {csa_0_4_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+0)
) csa_0_5 (
  .opA_i(ops_i[15])
  ,.opB_i(ops_i[16])
  ,.opC_i(ops_i[17])
  ,.res_o(csa_0_5_res_o)
  ,.car_o(csa_0_5_car_o)
);

wire [width_p+0:0] csa_internal_wire_10 = {1'b0, csa_0_5_res_o};
wire [width_p+0:0] csa_internal_wire_11 = {csa_0_5_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+1)
) csa_1_0 (
  .opA_i(csa_internal_wire_0)
  ,.opB_i(csa_internal_wire_1)
  ,.opC_i(csa_internal_wire_2)
  ,.res_o(csa_1_0_res_o)
  ,.car_o(csa_1_0_car_o)
);

wire [width_p+1:0] csa_internal_wire_12 = {1'b0, csa_1_0_res_o};
wire [width_p+1:0] csa_internal_wire_13 = {csa_1_0_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+1)
) csa_1_1 (
  .opA_i(csa_internal_wire_3)
  ,.opB_i(csa_internal_wire_4)
  ,.opC_i(csa_internal_wire_5)
  ,.res_o(csa_1_1_res_o)
  ,.car_o(csa_1_1_car_o)
);

wire [width_p+1:0] csa_internal_wire_14 = {1'b0, csa_1_1_res_o};
wire [width_p+1:0] csa_internal_wire_15 = {csa_1_1_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+1)
) csa_1_2 (
  .opA_i(csa_internal_wire_6)
  ,.opB_i(csa_internal_wire_7)
  ,.opC_i(csa_internal_wire_8)
  ,.res_o(csa_1_2_res_o)
  ,.car_o(csa_1_2_car_o)
);

wire [width_p+1:0] csa_internal_wire_16 = {1'b0, csa_1_2_res_o};
wire [width_p+1:0] csa_internal_wire_17 = {csa_1_2_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+1)
) csa_1_3 (
  .opA_i(csa_internal_wire_9)
  ,.opB_i(csa_internal_wire_10)
  ,.opC_i(csa_internal_wire_11)
  ,.res_o(csa_1_3_res_o)
  ,.car_o(csa_1_3_car_o)
);

wire [width_p+1:0] csa_internal_wire_18 = {1'b0, csa_1_3_res_o};
wire [width_p+1:0] csa_internal_wire_19 = {csa_1_3_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+2)
) csa_2_0 (
  .opA_i(csa_internal_wire_12)
  ,.opB_i(csa_internal_wire_13)
  ,.opC_i(csa_internal_wire_14)
  ,.res_o(csa_2_0_res_o)
  ,.car_o(csa_2_0_car_o)
);

wire [width_p+2:0] csa_internal_wire_20 = {1'b0, csa_2_0_res_o};
wire [width_p+2:0] csa_internal_wire_21 = {csa_2_0_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+2)
) csa_2_1 (
  .opA_i(csa_internal_wire_15)
  ,.opB_i(csa_internal_wire_16)
  ,.opC_i(csa_internal_wire_17)
  ,.res_o(csa_2_1_res_o)
  ,.car_o(csa_2_1_car_o)
);

wire [width_p+2:0] csa_internal_wire_22 = {1'b0, csa_2_1_res_o};
wire [width_p+2:0] csa_internal_wire_23 = {csa_2_1_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+3)
) csa_3_0 (
  .opA_i({1'b0, csa_internal_wire_18})
  ,.opB_i({1'b0, csa_internal_wire_19})
  ,.opC_i(csa_internal_wire_20)
  ,.res_o(csa_3_0_res_o)
  ,.car_o(csa_3_0_car_o)
);

wire [width_p+3:0] csa_internal_wire_24 = {1'b0, csa_3_0_res_o};
wire [width_p+3:0] csa_internal_wire_25 = {csa_3_0_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+3)
) csa_3_1 (
  .opA_i(csa_internal_wire_21)
  ,.opB_i(csa_internal_wire_22)
  ,.opC_i(csa_internal_wire_23)
  ,.res_o(csa_3_1_res_o)
  ,.car_o(csa_3_1_car_o)
);

wire [width_p+3:0] csa_internal_wire_26 = {1'b0, csa_3_1_res_o};
wire [width_p+3:0] csa_internal_wire_27 = {csa_3_1_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+4)
) csa_4_0 (
  .opA_i(csa_internal_wire_24)
  ,.opB_i(csa_internal_wire_25)
  ,.opC_i(csa_internal_wire_26)
  ,.res_o(csa_4_0_res_o)
  ,.car_o(csa_4_0_car_o)
);

wire [width_p+4:0] csa_internal_wire_28 = {1'b0, csa_4_0_res_o};
wire [width_p+4:0] csa_internal_wire_29 = {csa_4_0_car_o,1'b0};
bsg_adder_carry_save#(
  .width_p(width_p+5)
) csa_5_0 (
  .opA_i({1'b0, csa_internal_wire_27})
  ,.opB_i(csa_internal_wire_28)
  ,.opC_i(csa_internal_wire_29)
  ,.res_o(csa_5_0_res_o)
  ,.car_o(csa_5_0_car_o)
);

wire [width_p+5:0] csa_internal_wire_30 = {1'b0, csa_5_0_res_o};
wire [width_p+5:0] csa_internal_wire_31 = {csa_5_0_car_o,1'b0};

assign resA_o = csa_internal_wire_30;
assign resB_o = csa_internal_wire_31;
endmodule

