make DIMS_P=2 XY_ORDER=1
make DIMS_P=2 XY_ORDER=0
make DIMS_P=3 RUCHE_X=3 XY_ORDER=1
make DIMS_P=3 RUCHE_X=3 XY_ORDER=0
make DIMS_P=4 RUCHE_X=3 RUCHE_Y=2 XY_ORDER=1
make DIMS_P=4 RUCHE_X=3 RUCHE_Y=2 XY_ORDER=0

make NUM_X=7 NUM_Y=13 DIMS_P=4 RUCHE_X=3 RUCHE_Y=5 XY_ORDER=1
make NUM_X=7 NUM_Y=13 DIMS_P=4 RUCHE_X=3 RUCHE_Y=5 XY_ORDER=0
