
// ## AUTOGENERATED; DO NOT MODIFY
// ## num_rows_p = 8
// ## num_cols_p = 8
// ## num_dly_p = 8


module bsg_rp_clk_gen_osc_v3_row
 (input    async_reset_neg_i
  , input  async_set_neg_i
  , input  clkgate_i
  , input  clkdly_i
  , input  clkfb_i
  , input  ctl_i
  , output clk_o
  );

  wire ctl_r;
  SC7P5T_DFFRSQX1_SSC14SL D0(.Q(ctl_r), .CLK(clkgate_i), .D(ctl_i), .RESET(async_reset_neg_i), .SET(async_set_neg_i));

  wire ctl_en;
  SC7P5T_CKND2X1_SSC14SL N0 (.Z(ctl_en), .CLK(clkdly_i), .EN(ctl_r));

  wire lobit;
  SC7P5T_TIELOX2_SSC14SL T0 (.Z(lobit));
  wire hibit;
  SC7P5T_TIEHIX2_SSC14SL T1 (.Z(hibit));

  wire fb;
  SC7P5T_CKND2X1_SSC14SL N1 (.Z(fb), .CLK(clkfb_i), .EN(hibit));
  wire clk;
  SC7P5T_CKND2X1_SSC14SL N2 (.Z(clk), .CLK(fb), .EN(ctl_en));

  assign
`ifdef BSG_RP_CLK_GEN_SIM_DELAY
    #`BSG_RP_CLK_GEN_SIM_DELAY
`endif
  clk_o = clk;

endmodule


module bsg_rp_clk_gen_osc_v3_col
  (input async_reset_i
   , input clkgate_i
   , input clkdly_i
   , input clkfb_i
   , input [7:0] ctl_one_hot_i
   , output clk_o
   );

  wire lobit;
  SC7P5T_TIELOX2_SSC14SL T0 (.Z(lobit));
  wire hibit;
  SC7P5T_TIEHIX2_SSC14SL T1 (.Z(hibit));

  // Size to 1/4 of column load
  wire clkgate_inv;
  SC7P5T_CKINVX2_SSC14SL I0 (.Z(clkgate_inv), .CLK(clkgate_i));
  wire clkdly_inv;
  SC7P5T_CKINVX2_SSC14SL I1 (.Z(clkdly_inv), .CLK(clkdly_i));

  wire async_reset_neg;
  SC7P5T_INVX1_SSC14SL I2 (.Z(async_reset_neg), .A(async_reset_i));

  wire [8:0] clkfb;
  SC7P5T_CKBUFX1_SSC14SL B0 (.Z(clkfb[0]), .CLK(clkfb_i));

  wire [7:0] async_reset_neg_li, async_set_neg_li;


       assign async_reset_neg_li[0] = hibit;
       assign async_set_neg_li[0]   = async_reset_neg;
     

       bsg_rp_clk_gen_osc_v3_row row_0
         (.async_reset_neg_i(async_reset_neg_li[0])
          ,.async_set_neg_i(async_set_neg_li[0])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[0])
          ,.ctl_i(ctl_one_hot_i[0])
          ,.clk_o(clkfb[1])
          );


       assign async_reset_neg_li[1] = async_reset_neg;
       assign async_set_neg_li[1]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_1
         (.async_reset_neg_i(async_reset_neg_li[1])
          ,.async_set_neg_i(async_set_neg_li[1])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[1])
          ,.ctl_i(ctl_one_hot_i[1])
          ,.clk_o(clkfb[2])
          );


       assign async_reset_neg_li[2] = async_reset_neg;
       assign async_set_neg_li[2]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_2
         (.async_reset_neg_i(async_reset_neg_li[2])
          ,.async_set_neg_i(async_set_neg_li[2])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[2])
          ,.ctl_i(ctl_one_hot_i[2])
          ,.clk_o(clkfb[3])
          );


       assign async_reset_neg_li[3] = async_reset_neg;
       assign async_set_neg_li[3]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_3
         (.async_reset_neg_i(async_reset_neg_li[3])
          ,.async_set_neg_i(async_set_neg_li[3])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[3])
          ,.ctl_i(ctl_one_hot_i[3])
          ,.clk_o(clkfb[4])
          );


       assign async_reset_neg_li[4] = async_reset_neg;
       assign async_set_neg_li[4]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_4
         (.async_reset_neg_i(async_reset_neg_li[4])
          ,.async_set_neg_i(async_set_neg_li[4])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[4])
          ,.ctl_i(ctl_one_hot_i[4])
          ,.clk_o(clkfb[5])
          );


       assign async_reset_neg_li[5] = async_reset_neg;
       assign async_set_neg_li[5]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_5
         (.async_reset_neg_i(async_reset_neg_li[5])
          ,.async_set_neg_i(async_set_neg_li[5])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[5])
          ,.ctl_i(ctl_one_hot_i[5])
          ,.clk_o(clkfb[6])
          );


       assign async_reset_neg_li[6] = async_reset_neg;
       assign async_set_neg_li[6]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_6
         (.async_reset_neg_i(async_reset_neg_li[6])
          ,.async_set_neg_i(async_set_neg_li[6])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[6])
          ,.ctl_i(ctl_one_hot_i[6])
          ,.clk_o(clkfb[7])
          );


       assign async_reset_neg_li[7] = async_reset_neg;
       assign async_set_neg_li[7]   = hibit;
     

       bsg_rp_clk_gen_osc_v3_row row_7
         (.async_reset_neg_i(async_reset_neg_li[7])
          ,.async_set_neg_i(async_set_neg_li[7])
          ,.clkgate_i(clkgate_inv)
          ,.clkdly_i(clkdly_inv)
          ,.clkfb_i(clkfb[7])
          ,.ctl_i(ctl_one_hot_i[7])
          ,.clk_o(clkfb[8])
          );


  assign clk_o = clkfb[8];

endmodule

