# Simulator choice (vcs or verilator)
#export SIM=vcs
export SIM :=verilator

# Configuration file name
export CFG :=config.json

# Include the rest of the cocotb testing infrastructure.
include ../../Makefile.common
