
// ## AUTOGENERATED; DO NOT MODIFY
// ## num_rows_p = 2
// ## num_cols_p = 2
// ## num_dly_p = 4


  module bsg_rp_dly_line_ctl_reg
    (input clk_i
     , input async_reset_neg
     , input async_set_neg
     , input shift_right
     , input shift_left
     , input counter_en
     , input ctl_m1
     , input ctl_p1
     , output ctl_o
     );

    wire set_left, set_right, set;
    wire ctl_n, ctl_r;

    sky130_fd_sc_hd__and2 A0 (.A(shift_right), .B(ctl_m1), .X(set_right));
    sky130_fd_sc_hd__and2 A1 (.A(shift_left), .B(ctl_p1), .X(set_left));
    sky130_fd_sc_hd__or2 O0 (.A(set_left), .B(set_right), .X(set));
    sky130_fd_sc_hd__mux2 M0 (.X(ctl_n), .S(counter_en), .A0(ctl_r), .A1(set));
    sky130_fd_sc_hd__dfbbp D0 (.Q(ctl_r), .Q_N(), .CLK(clk_i), .D(ctl_n), .RESET_B(async_reset_neg), .SET_B(async_set_neg));

    assign ctl_o = ctl_r;

endmodule



  module bsg_rp_dly_line_unit_v3
      (input async_reset_i
      , input trigger_i
      , input [3:0] ctl_one_hot_i
      , input  clk_i
      , output clk_o
      );
      wire lobit, hibit;
      sky130_fd_sc_hd__conb T0 (.HI(hibit) .LO(lobit));
  

  wire fb_inv;
  sky130_fd_sc_hd__clkinv I0 (.Y(fb_inv), .A(clk_i));
  wire gate_en_sync_1_r, gate_en_sync_2_r;
  sky130_fd_sc_hd__dfxtp S1 (.D(trigger_i), .CLK(clk_i), .Q(gate_en_sync_1_r));
  sky130_fd_sc_hd__dfxtp S2 (.D(gate_en_sync_1_r), .CLK(clk_i), .Q(gate_en_sync_2_r));
  wire fb_gated;
  sky130_fd_sc_hd__dlclkp CG0 (.GCLK(fb_gated), .CLK(clk_i), .GATE(gate_en_sync_2_r));
  wire [2:0] fb_col;
  assign fb_col[0] = 1'b0;


      bsg_rp_clk_gen_osc_v3_col col_0_BSG_DONT_TOUCH
       (.async_reset_i(async_reset_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(fb_inv)
        ,.clkfb_i(fb_col[0])
        ,.ctl_one_hot_i(ctl_one_hot_i[1:0])
        ,.clk_o(fb_col[1])
        );


      bsg_rp_clk_gen_osc_v3_col col_1_BSG_DONT_TOUCH
       (.async_reset_i(async_reset_i)
        ,.clkgate_i(fb_gated)
        ,.clkdly_i(fb_inv)
        ,.clkfb_i(fb_col[1])
        ,.ctl_one_hot_i(ctl_one_hot_i[3:2])
        ,.clk_o(fb_col[2])
        );


  sky130_fd_sc_hd__clkbuf B0 (.X(clk_o), .A(fb_col[2]));
endmodule


  module bsg_rp_dly_line_v3
   (input async_reset_i
    , input clk_i
    , output clk_o
    );

  wire lobit, hibit;
  sky130_fd_sc_hd__conb T0 (.HI(hibit), .LO(lobit));
  wire async_reset_neg;
  sky130_fd_sc_hd__inv I0 (.Y(async_reset_neg), .A(async_reset_i));
  // State machine
  // Trigger off
  wire trigger_off, trigger_on;
  sky130_fd_sc_hd__dfstp D0 (.Q(trigger_off), .CLK(clk_i), .D(trigger_on), .SET_B(async_reset_neg));
  // Change counter
  wire counter_en;
  sky130_fd_sc_hd__dfrtp D1 (.Q(counter_en), .CLK(clk_i), .D(trigger_off), .RESET_B(async_reset_neg));
  // Pause
  wire pause;
  sky130_fd_sc_hd__dfrtp D2 (.Q(pause), .CLK(clk_i), .D(counter_en), .RESET_B(async_reset_neg));
  // Trigger on
  sky130_fd_sc_hd__dfrtp D3 (.Q(trigger_on), .CLK(clk_i), .D(pause), .RESET_B(async_reset_neg));
  wire [4-1:0] ctl_n, ctl_r;
  wire clk_90;
  bsg_rp_dly_line_unit_v3 d90_BSG_DONT_TOUCH
   (.async_reset_i(async_reset_i)
    ,.trigger_i(trigger_on)
    ,.ctl_one_hot_i(ctl_r[3:0])
    ,.clk_i(clk_i)
    ,.clk_o(clk_90)
    );
  bsg_rp_dly_line_unit_v3 d180_BSG_DONT_TOUCH
   (.async_reset_i(async_reset_i)
    ,.trigger_i(trigger_on)
    ,.ctl_one_hot_i(ctl_r[3:0])
    ,.clk_i(clk_90)
    ,.clk_o(clk_180)
    );
  wire [4:0] n;
  assign n[0] = clk_180;


    sky130_fd_sc_hd__clkbuf B0 (.X(n[1]), .A(n[0]));


    sky130_fd_sc_hd__clkbuf B1 (.X(n[2]), .A(n[1]));


    sky130_fd_sc_hd__clkbuf B2 (.X(n[3]), .A(n[2]));


    sky130_fd_sc_hd__clkbuf B3 (.X(n[4]), .A(n[3]));


  // Delay value ignored in synthesis
  wire #100 clk_dly = n[4];

  wire lobit, hibit;
  sky130_fd_sc_hd__conb T0 (.HI(hibit) .LO(lobit));

  wire meta;
  sky130_fd_sc_hd__dfrtn meta_r (.Q(meta), .CLKN(clk_i), .RESET_B(async_reset_neg), .D(clk_dly));
  wire meta_sync, meta_sync_sync, meta_sync_sync_inv;
  sky130_fd_sc_hd__dfrbp bsg_SYNC_1_r (.Q(meta_sync), .Q_N(), .CLK(clk_i), .D(meta), .RESET_B(async_reset_neg));
  sky130_fd_sc_hd__dfrbp bsg_SYNC_2_r (.Q(meta_sync_sync), .Q_N(meta_sync_sync_inv), .CLK(clk_i), .D(meta_sync), .RESET_B(async_reset_neg));
  wire shift_left = meta_sync_sync;
  wire shift_right = meta_sync_sync_inv;
  wire [4-1:0] set_right, set_left, set;


    bsg_rp_dly_line_ctl_reg ctl_0
     (.clk_i(clk_i)
      ,.async_reset_neg(async_reset_neg)
      ,.async_set_neg(hibit)
      ,.shift_right(shift_left)
      ,.shift_left(shift_left)
      ,.counter_en(counter_en)

      ,.ctl_m1(ctl_r[0])
      ,.ctl_p1(ctl_r[1])
      ,.ctl_o(ctl_r[0])
      );


    bsg_rp_dly_line_ctl_reg ctl_1
     (.clk_i(clk_i)
      ,.async_reset_neg(async_reset_neg)
      ,.async_set_neg(hibit)
      ,.shift_right(shift_right)
      ,.shift_left(shift_left)
      ,.counter_en(counter_en)

      ,.ctl_m1(ctl_r[0])
      ,.ctl_p1(ctl_r[2])
      ,.ctl_o(ctl_r[1])
      );
  

    bsg_rp_dly_line_ctl_reg ctl_2
     (.clk_i(clk_i)
      ,.async_reset_neg(async_reset_neg)
      ,.async_set_neg(hibit)
      ,.shift_right(shift_right)
      ,.shift_left(shift_left)
      ,.counter_en(counter_en)

      ,.ctl_m1(ctl_r[1])
      ,.ctl_p1(ctl_r[3])
      ,.ctl_o(ctl_r[2])
      );
  

    bsg_rp_dly_line_ctl_reg ctl_3
     (.clk_i(clk_i)
      ,.async_reset_neg(hibit)
      ,.async_set_neg(async_reset_neg)
      ,.shift_right(shift_right)
      ,.shift_left(shift_right)
      ,.counter_en(counter_en)

      ,.ctl_m1(ctl_r[2])
      ,.ctl_p1(ctl_r[3])
      ,.ctl_o(ctl_r[3])
      );


    assign clk_o = clk_90;

  endmodule

