// 64-bit version of modular inverse using Extended Euclid
// generated by ChatGPT 5 Thinking

  function automatic longint unsigned modinv64
  (
    input  longint unsigned a,
    input  longint unsigned m,
    output bit              ok
  );
    longint signed t  = 0;
    longint signed nt = 1;
    longint signed r  = longint'(m);
    longint signed nr = (m == 0) ? 0 : longint'(a % m);

    if (m == 0) begin ok = 0; return '0; end
    if (nr == 0) begin ok = 0; return '0; end

    while (nr != 0) begin
      longint signed q = r / nr;

      longint signed tmp;
      tmp = t  - q*nt;  t  = nt;  nt = tmp;
      tmp = r  - q*nr;  r  = nr;  nr = tmp;
    end

    if (r != 1) begin ok = 0; return '0; end
    // normalize into [0, m-1]    
    if (t < 0) t = t + longint'(m);
    ok = 1;
    return t;
  endfunction
